### ISSUE TITLE
Unknown parameter -os

### ISSUE THREAD

**Issue by ttjaden** [ONLYOFFICE/Docker-CommunityServer#102]
Setting:

> Ubuntu Server 20.04 LTS
> OnlyOffice CE installed with opensource-install.sh -ims false

The last Update (few months ago) worked like a charm. But now: 

Problem:
`bash opensource-install.sh -u true`
results in 
`Unknown parameter -os`

**Comment by Carazyda** [comment]
Hello @ttjaden In close time we will update the helpcenter and instructions. Stay tuned.

**Comment by ttjaden** [comment]
I close the issue because update with the new workspace-install.sh worked!
