### ISSUE TITLE
Fails to start - "freezing execution"

### ISSUE THREAD

**Issue by aaronouthier** [ONLYOFFICE/Docker-CommunityServer#104]
Hello,
I used git clone to grab the docker source, and edited the docker-compose.yml to add the name of the mail server. I then issued "docker-compose up -d"

When the web server never came up, I checked the logs. Seems there are some major issues mounting filesystems:
```
onlyoffice-community-server    | 2020-10-20T03:33:18.262462898Z Executing: /lib/systemd/systemd-sysv-install enable nginx
onlyoffice-community-server    | 2020-10-20T03:33:18.296055532Z ++ ps auxf
onlyoffice-community-server    | 2020-10-20T03:33:18.296082581Z ++ grep cron
onlyoffice-community-server    | 2020-10-20T03:33:18.296375813Z ++ grep -v grep
onlyoffice-community-server    | 2020-10-20T03:33:18.296589414Z ++ awk '{print $2}'
onlyoffice-community-server    | 2020-10-20T03:33:18.301281715Z + PID=
onlyoffice-community-server    | 2020-10-20T03:33:18.301302379Z + '[' ']'
onlyoffice-community-server    | 2020-10-20T03:33:18.301312656Z + systemctl enable elasticsearch.service
onlyoffice-community-server    | 2020-10-20T03:33:18.306087248Z Synchronizing state of elasticsearch.service with SysV service script with /lib/systemd/systemd-sysv-install.
onlyoffice-community-server    | 2020-10-20T03:33:18.306108721Z Executing: /lib/systemd/systemd-sysv-install enable elasticsearch
onlyoffice-community-server    | 2020-10-20T03:33:18.347503946Z Created symlink /etc/systemd/system/multi-user.target.wants/elasticsearch.service ��� /usr/lib/systemd/system/elasticsearch.service.
onlyoffice-community-server    | 2020-10-20T03:33:18.348367896Z + '[' -n '' ']'
onlyoffice-community-server    | 2020-10-20T03:33:18.348405351Z + '[' true == true ']'
onlyoffice-community-server    | 2020-10-20T03:33:18.348420589Z + exec /lib/systemd/systemd
onlyoffice-community-server    | 2020-10-20T03:33:18.354131178Z Failed to mount tmpfs at /run: Operation not permitted
onlyoffice-community-server    | 2020-10-20T03:33:18.354156405Z Failed to mount tmpfs at /run/lock: Operation not permitted
onlyoffice-community-server    | 2020-10-20T03:33:18.354638501Z Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
onlyoffice-community-server    | 2020-10-20T03:33:18.354660675Z [!!!!!!] Failed to mount API filesystems, freezing.
onlyoffice-community-server    | 2020-10-20T03:33:18.354714684Z Freezing execution.
onlyoffice-mail-server         | 2020-10-20T03:33:32.686170046Z [ INFO ] Configure OpenDkim.
```

**Comment by aaronouthier** [comment]
Let me know if you need the full log.

**Comment by aaronouthier** [comment]
Oh, forgot to mention: The host system is a bare-metal install of Ubuntu "focal".

**Comment by aaronouthier** [comment]
[onlyoffice.log](https://github.com/ONLYOFFICE/Docker-CommunityServer/files/5408843/onlyoffice.log)
Full Logfile.
By the way, This is a fresh server install as of about 4 days ago.

**Comment by aaronouthier** [comment]
I got it WoRkInG!!
I had to create 2 additional folders inside my onlyoffice working folder: run and lock.
I also had to mount tmpfs inside of each:
```
mount -t tmpfs -o nosuid,noexec tmpfs run
mount -t tmpfs -o nosuid,noexec tmpfs lock
```
Then, I modified docker-compose.yml to include a few more volumes for the community server. See my attached docker-compose file.
[docker-compose.yml.txt](https://github.com/ONLYOFFICE/Docker-CommunityServer/files/5415605/docker-compose.yml.txt)

**Comment by aaronouthier** [comment]
Important!! The two mount commands MUST be run before running starting the docker containers. It should probably be done at system startup.

**Comment by Carazyda** [comment]
Hello @aaronouthier you need add one more mount to docker run. In close time we will update instructions on github.
`-v /sys/fs/cgroup:/sys/fs/cgroup:ro`

**Comment by aaronouthier** [comment]
Yes, I already figured this out on my own. Besides the one you mentioned, you also need, /sys/fs/cgroup/systemd:/sys/fs/cgroup/systemd:ro

The container also needs a read/write tmpfs mounted in /run and another one in /run/lock .

I am using a docker-compose file in order to simplify things. I attached my docker-compose.yml in a previous post for reference.

It seems that you are on top of this, however.

**Comment by aaronouthier** [comment]
Someone else filed a bug report in another section:
https://github.com/ONLYOFFICE/CommunityServer/issues/255
There is a similar discussion there.

**Comment by SuberSeb** [comment]
> you need add one more mount to docker run. In close time we will update instructions on github.

What if I don't have systemd there?

**Comment by aaronouthier** [comment]
@SuberSeb Please be specific: don’t have systemd where? On the host machine?

I’m not aware of any modern Linux distros that don’t support systemd.

Please describe your issue in a bit more detail.

**Comment by SuberSeb** [comment]
> @SuberSeb Please be specific: don’t have systemd where? On the host machine?
> 
> I’m not aware of any modern Linux distros that don’t support systemd.
> 
> Please describe your issue in a bit more detail.

I have unraid os as my host system, seems it doesn't have systemd.

**Comment by aaronouthier** [comment]
Wow! That was a quick response!

Ok, I’ve heard of unraid, but never used it. I’m also not familiar with it, I’ve only seen references to it around the ‘net. If it is Linux-based, but doesn’t use systemd, then I’m not sure how to help in that case. If you’re able to add it, you could try that. Otherwise, try a virtualbox or kvm virtual machine.

**Comment by sasha986** [comment]
I have fixed docker-compose.yml with added two lines of code.... Should I create pull request? 
Basically, in docker-compose.yml is missing under onlyoffice-community-server two lines of code which will fix the issue.
example below
```
onlyoffice-community-server: 
    privileged: true
    ....
    volumes:
        - ....
        - /sys/fs/cgroup:/sys/fs/cgroup
    ....
```

**Comment by aaronouthier** [comment]
> I have fixed docker-compose.yml with added two lines of code.... Should I create pull request?
> Basically, in docker-compose.yml is missing under onlyoffice-community-server two lines of code which will fix the issue.
> example below
> 
> ```
> onlyoffice-community-server: 
>     privileged: true
>     ....
>     volumes:
>         - ....
>         - /sys/fs/cgroup:/sys/fs/cgroup
>     ....
> ```

Yes, this worked and fixed the problem for me. Since your post, the developers have fixed the problem.
In order to update, you will need to discard changes to your onlyoffice folder. This won't lose any documents or data stored in onlyoffice.

To get the updates, first CD to the OnlyOffice folder, then:
```
docker exec onlyoffice-document-server documentserver-prepare4shutdown.sh
docker-compose down
git stash
git pull
```
Then, edit docker-compose.workspace.yml to add your mail server again, using your favorite text editor, also make a symlink from docker-compose.workspace.yml to docker-compose.yml with
`ln -s docker-compose.workspace.yml docker-compose.yml`

Finally, issue the commands:
```
docker-compose pull
docker-compose up -d
```

Issue closed.

**Comment by pelaxa** [comment]
@SuberSeb did you ever figure out your issue?  I cannot start community server on unraid because of this error.
