### ISSUE TITLE
upgrade community server 10.0.4.1001 to 10.5.1.1028

### ISSUE THREAD

**Issue by filippolmt** [ONLYOFFICE/Docker-CommunityServer#105]
Hi, I'm trying to update the community server from version 10.0.4.1001 to version 10.5.1.1028 without success, the container starts without errors but the web page redirects to https: //domainname/tariffs.aspx with error in the response: ERR_TOO_MANY_REDIRECTS .

My intent is to update the service to the latest release.

**Comment by Carazyda** [comment]
Hello @filippolmt Please describe how you run docker containers and how you update it? Redirect in /tariffs.aspx means that you try use version not included to your license. Also you can try update to 11.0 version.

**Comment by filippolmt** [comment]
Hi,
Here is the docker-compose:
`version: '3.5'
services:
  tonlyoffice-mysql-server:
    container_name: tonlyoffice-mysql-server
    image: mysql:5.7.21
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    networks:
     - tonlyoffice
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - ./config/mysql/conf.d:/etc/mysql/conf.d
     - ./config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     - tmysql_data:/var/lib/mysql
  tonlyoffice-community-server:
    container_name: tonlyoffice-community-server
    #image: onlyoffice/communityserver:latest
    #image: onlyoffice/communityserver:10.5.3.1172
    #image: onlyoffice/communityserver:10.5.1.1028
    image: onlyoffice/communityserver:10.0.4.1001
    depends_on:
     - tonlyoffice-mysql-server
     - tonlyoffice-document-server
     - tonlyoffice-mail-server
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=xxxxxx
     - DOCUMENT_SERVER_PORT_80_TCP_ADDR=tonlyoffice-document-server
     - MYSQL_SERVER_ROOT_PASSWORD=my-secret-pw
     - MYSQL_SERVER_DB_NAME=onlyoffice
     - MYSQL_SERVER_HOST=tonlyoffice-mysql-server
     - MYSQL_SERVER_USER=onlyoffice_user
     #- DOCUMENT_SERVER_JWT_SECRET=jwt_secret
     #- DOCUMENT_SERVER_JWT_HEADER=AuthorizationJwt
     - MYSQL_SERVER_PASS=onlyoffice_pass
     - MAIL_SERVER_API_PORT=8081
     - MAIL_SERVER_API_HOST=tonlyoffice-mail-server
     - MAIL_SERVER_DB_HOST=tonlyoffice-mysql-server
     - MAIL_SERVER_DB_PORT=3306
     - MAIL_SERVER_DB_NAME=onlyoffice_mailserver
     - MAIL_SERVER_DB_USER=onlyoffice_mailserver_user
     - MAIL_SERVER_DB_PASS=onlyoffice_mailserver_user_pass
    networks:
     - tonlyoffice
    ports:
     - '90:80'
     - '450:443'
     - '5223:5222'
    stdin_open: true
     tty: true
    expose:
      - '8081'
    volumes:
      - tmail_data:/var/vmail
      - tmail_certs:/etc/pki/tls/mailserver
      - tmail_log:/var/log
networks:
  tonlyoffice:
    name: tonlyoffice
    driver: 'bridge'
volumes:
  tmail_data:
  tmail_certs:
  tmail_log:
  tdocument_data:
  tdocument_log:
  tdocument_forgotten:
  tcommunity_data:
  tcommunity_log:
  tmysql_data:
  tcerts:
  tdocument_fonts:`

I wanted to add that I migrated from the enterprise version to the community version, so I imported the db and moved the files to the Products folder.
I started from version onlyoffice / communityserver: 10.0.4.959 and I updated without problems to version onlyoffice / communityserver: 10.0.4.1000 and then to version onlyoffice / communityserver: 10.0.4.1001 the problem arose when updating to version onlyoffice / communityserver: 10.5 .1.1028.

I tried to upgrade directly to version 11 but it gives the same result.

**Comment by Carazyda** [comment]
You can try use backup\restore function, because we don't include license to backup file. Make backup on 10.0, and restore on a fresh 11.0 installation.

**Comment by filippolmt** [comment]
> You can try use backup\restore function, because we don't include license to backup file. Make backup on 10.0, and restore on a fresh 11.0 installation.

I am currently unable to do this, can I delete the key from the database? or carry out some operation?
