### ISSUE TITLE
High RAM usage in Idle

### ISSUE THREAD

**Issue by dev-nm** [ONLYOFFICE/Docker-CommunityServer#112]
HI!
I have a pretty fresh installation of OnlyOffice running on my server. As it is still for testing pourposes there are no other users than me , the system is pretty much in Idle the whole time. Unfortunatly I have very high RAM usage - 4+ GB RAM in Idle by elastisearch alone. But as Full-Text-Search is turned of (As I dont own a License right now) there should not be a lot of RAM usage as far as I know...

Combined OnlyOffice Uses arround 8.5 GB Of RAM in Idle - which too seems to be a lot to me. Anyone a Suggestion how to reduce this? Or is this just normal behavior of OnlyOffice?

Thanks a lot for your Time!

**Comment by Carazyda** [comment]
Hello @ dev-nm full-text search is turned on by default. In Control Panel you can additional enable search on content of documents and mail. In new 11.0 version this is free function, and you don't need a license for it. Yes, elasticsearch used a lot of resources, and it normal. In idle all Onlyoffice services are working, and use resources. Our minimal requirements are 6gb ram and 4gb swap. In your case not all of 8.5gb in use, part of them in cache \ buffer.

**Comment by dev-nm** [comment]
Ok, thanks for the Information! Unfortunately I am not able to update. I get following Error Message. But I got this from the start with a fresh Install of OnlyOffice with Docker just installed...

Do you know how how to fix this?

![71DA9C4B-5DFC-4BCC-BBBA-F448A794D571](https://user-images.githubusercontent.com/22733587/100205640-ac7ac100-2f05-11eb-9912-3bc214284c10.jpeg)

**Comment by Carazyda** [comment]
How did you install Onlyoffice, manual or use our script? Please run this commands in your controlpanel container:
`docker exec -it onlyoffice-control-panel bash`
`docker ps -a`
`bash www/executables/tools/get-current-version.sh onlyoffice-community-server`

**Comment by dev-nm** [comment]
This is the Output:

`root@vmd63537:/app/onlyoffice/CommunityServer/logs# docker exec -it onlyoffice-control-panel bash
root@8ab9245581fa:/var/www/onlyoffice/controlpanel# docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                                                                     NAMES
e66fd7058fa2        onlyoffice/communityserver   "/app/run-communit..."   5 days ago          Up 5 days           3306/tcp, 5222/tcp, 5280/tcp, 9865-9866/tcp, 9871/tcp, 9882/tcp, 9888/tcp, 0.0.0.0:5080->80/tcp, 0.0.0.0:5443->443/tcp    onlyoffice-community-server
8ab9245581fa        onlyoffice/controlpanel      "/var/www/onlyoffi..."   5 days ago          Up 5 days           80/tcp, 443/tcp, 9833-9834/tcp                                                                                            onlyoffice-control-panel
777d3334617b        onlyoffice/mailserver        "/bin/sh -c 'expor..."   5 days ago          Up 5 days           0.0.0.0:25->25/tcp, 0.0.0.0:143->143/tcp, 465/tcp, 993/tcp, 995/tcp, 3306/tcp, 4190/tcp, 0.0.0.0:587->587/tcp, 8081/tcp   onlyoffice-mail-server
d58b6ba82aaa        onlyoffice/documentserver    "/bin/sh -c /app/d..."   5 days ago          Up 5 days           80/tcp, 443/tcp                                                                                                           onlyoffice-document-server
7f02bcca6cc4        mysql:5.7                    "docker-entrypoint..."   5 days ago          Up 5 days           0.0.0.0:3306->3306/tcp, 33060/tcp                                                                                         onlyoffice-mysql-server
root@8ab9245581fa:/var/www/onlyoffice/controlpanel# bash www/executables/tools/get-current-version.sh onlyoffice-community-server

root@8ab9245581fa:/var/www/onlyoffice/controlpanel# `

I found another Problem: I cant upload Documents at all. I get an "Unknown Error" Every time. Searching inside the Logs in /app/onlyoffice/CommunityServer/logs I have not found anything showing more Information.

**Comment by Carazyda** [comment]
All your problems because you not properly installed onlyoffice docker containers. Please try use our script (see [instructions](https://helpcenter.onlyoffice.com/installation/workspace-install-docker.aspx). If you need to change default port for communityserver - you can use additional parameter for script `-cp 8080`.

**Comment by dev-nm** [comment]
Why isnt this Parameter listed in [your Documentation](https://helpcenter.onlyoffice.com/installation/workspace-install-docker-parameters.aspx)? And I will need to change the 443 and 5222 port too, as other applications use them allready.

**Comment by andreysavihin** [comment]
Hi, @dev-nm ! You can try to change installation script 

wget https://download.onlyoffice.com/install/install.sh

line 1387  

args+=(-p "$COMMUNITY_PORT:80");
args+=(-p 443:443);

then run changed script with parameters

bash install.sh -it WORKSPACE [... another parameters]

**Comment by dev-nm** [comment]
I did exacly that and installed onlyoffice on a clean Server. Everything seemed to work fine. I could upload, edit, update. But as soon as I installed an SLL Certificate on Nginx I get mixed Content Errors stating that a SSL Encrypted site tryes to load content over http so it is blocked. I tryed to activate https inside of OnlyOffice but same Problem.

Config is nginx on Server X is transmitting all traffic for Subdomain cloud.mydomain.com to 127.0.0.1:6080

Here is Nginx Cnfig:
```
server {
    server_name cloud.mydomain.com;
    location / {
        proxy_pass      http://127.0.0.1:6080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    client_max_body_size 0;


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/cloud.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cloud.mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = cloud.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name cloud.mydomain.com;
    listen 80;
    return 404; # managed by Certbot

}
```


And here are all Error Messages:
Nginx SSL + Onlyoffice
`Mixed Content: The page at 'https://cloud.mydomain.com/Products/Files/#1' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://cloud.mydomain.com/Products/Files/ChunkedUploader.ashx?uid=0ac0b16d8ec448f18f18d725fb1504ac'. This request has been blocked; the content must be served over HTTPS.`

Nginx SSL + OnlyOffice SSL (generated by onlyoffice)
`Mixed Content: The page at 'https://cloud.mydomain.com/Products/Files/#1' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://_/Products/Files/ChunkedUploader.ashx?uid=afe0def9c72e4787b6b0ed6173584b66'. This request has been blocked; the content must be served over HTTPS.`

**Comment by Carazyda** [comment]
Seems you don't have some headers in nginx config. Please look at our template [config](https://github.com/ONLYOFFICE/CommunityServer/blob/master/build/install/deb/Files/nginx/includes/onlyoffice-communityserver-common-ssl.conf.template).

**Comment by dev-nm** [comment]
Unfortunatly I dont really know how to configure this. There are a lot of Vars in it I dont know. Also If I try to configure it with this Configuration, my other services wont load anymore and keep returning 502's.
My config looks like this right now:

```
upstream fastcgi_backend_apisystem {
        server unix:/var/run/onlyoffice/onlyofficeApiSystem.socket;
        keepalive 32;
}

# === Dont know Variable {{APP_NIGNX_KEEPLIVE}}
#upstream fastcgi_backend {
#	server unix:/var/run/onlyoffice/onlyoffice.socket;
#	keepalive {{APP_NIGNX_KEEPLIVE}};
#}

# === Nginx returns it cant find /var/cache/nginx/onlyoffice
#fastcgi_cache_path /var/cache/nginx/onlyoffice
#	levels=1:2
#	keys_zone=onlyoffice:256m
#	max_size=1024m
#	inactive=1d;

# === Dont know Variable {{DOCKER_APP_SUBNET}}
#geo $ip_external {
#     default 1;
#     {{DOCKER_APP_SUBNET}} 0;
#     127.0.0.1 0;
#}

map $http_host $this_host {
  "" $host;
  default $http_host;
}

map $http_x_forwarded_proto $the_scheme {
  default $http_x_forwarded_proto;
  "" $scheme;
}

map $http_x_forwarded_host $the_host {
  default $http_x_forwarded_host;
  "" $this_host;
}

map $request_uri $header_access_control_allow_origin {
  ~*^/(api\/2.0|products\/crm\/httphandlers\/webtoleadfromhandler.ashx|products\/files\/httphandlers\/filehandler.ashx|products\/files\/chunkeduploader.ashx|thirdparty\/plugin) "*";
  default "";
}

map $request_uri $header_x_frame_options {
  ~*^/(favicon\.ico|products\/files\/share\.aspx|products\/files\/saveas\.aspx|products\/files\/filechoice\.aspx|products\/files\/doceditor\.aspx|thirdparty\/plugin) "";
  default "SAMEORIGIN";
}



server {
    server_name cloud.mydomain.com;
    location / {
        proxy_pass      http://127.0.0.1:6080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    client_max_body_size 0;
	server_tokens off;


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/cloud.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/cloud.mydomain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
	
	large_client_header_buffers 4 16k;
	
	set $X_REWRITER_URL $the_scheme://$the_host;

	if ($http_x_rewriter_url != '') {
		set $X_REWRITER_URL $http_x_rewriter_url ;
	}

    include /etc/nginx/includes/onlyoffice-communityserver-*.conf;

}
server {
    if ($host = cloud.mydomain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name cloud.mydomain.com;
    listen 80;
    return 404; # managed by Certbot

}
```

**Comment by dev-nm** [comment]
Seriusly, I dont get it... I install Onlyoffice on a clean Server. Cant connect via Domain only via Ip, so I install nginx configure it to connect without SSL - everything works. I can Upload, Download, Edit. Bus as soon as I install SSL - does not matter if I install it on the Nginx or if I install it inside of the control pannel - it does not work anymore. Isnt there a Tutorial to follow to install OnlyOffice on a Server with a Domain to connecting to it and activating SSL?!  I cant find anything regarding this - only tutorials for Docs only.

**Comment by Carazyda** [comment]
Please try add this headers to your config
`proxy_set_header X-Forwarded-Host $server_name;`
`proxy_set_header X-Forwarded-Proto $scheme;`

**Comment by dev-nm** [comment]
I got it working. It cost me some hours of trial and error but I got a nginx config that works.

For everybody how is facing the same Problem - here is how I fixed it:

1. Install OnlyOffice with Docker but with a different Port
    1.1 `wget https://download.onlyoffice.com/install/workspace-install.sh`
    1.2 `bash workspace-install.sh -md "yourdomain.com" -cp 6080`
    1.3 follow directions
2. Install nginx
    2.1 `sudo apt install nginx nginx-extras`
    2.2 `sudo unlink /etc/nginx/sites-enabled/default`
3. Configure nginx to acces onlyoffice without
    3.1 nano /etc/nginx/sites-available/onlyoffice.conf
```
server {
    server_name yourdomain.com;
    location / {
        proxy_pass      http://127.0.0.1:6080;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    client_max_body_size 0;
}
```
    3.2 `sudo ln -s /etc/nginx/sites-available/onlyoffice.conf /etc/nginx/sites-enabled/onlyoffice.conf`
4. Go into the OnlyOffice Control Panel and activate HTTPS
5. Change the Nginx config
    5.1 `nano /etc/nginx/sites-available/onlyoffice.conf`
```
upstream fastcgi_backend_apisystem {
        server unix:/var/run/onlyoffice/onlyofficeApiSystem.socket;
        keepalive 32;
}

upstream fastcgi_backend {
        server unix:/var/run/onlyoffice/onlyoffice.socket;
        keepalive 32;
}

fastcgi_cache_path /var/cache/nginx/onlyoffice
        levels=1:2
        keys_zone=onlyoffice:256m
        max_size=1024m
        inactive=1d;


map $request_uri $header_access_control_allow_origin {
  ~*^/(api\/2.0|products\/crm\/httphandlers\/webtoleadfromhandler.ashx|products\/files\/httphandlers\/filehandler.ashx|products\/files\/chunkeduploader.ashx|thirdpa$
  default "";
}

map $request_uri $header_x_frame_options {
  ~*^/(favicon\.ico|products\/files\/share\.aspx|products\/files\/saveas\.aspx|products\/files\/filechoice\.aspx|products\/files\/doceditor\.aspx|thirdparty\/plugin$
  default "SAMEORIGIN";
}

server {
    server_name yourdomain.com;

    ssl_certificate /app/onlyoffice/CommunityServer/data/certs/onlyoffice.crt;
    ssl_certificate_key /app/onlyoffice/CommunityServer/data/certs/onlyoffice.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;
    ssl_protocols TLSv1.2;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:EC$    ssl_prefer_server_ciphers off;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options $header_x_frame_options;
    add_header X-Content-Type-Options nosniff;
    add_header Access-Control-Allow-Origin $header_access_control_allow_origin;


    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate /app/onlyoffice/CommunityServer/data/certs/stapling.trusted.crt;
    resolver 8.8.8.8 8.8.4.4 127.0.0.11 valid=300s; # Can change to your DNS resolver if desired
    resolver_timeout 10s;

    ssl_dhparam /app/onlyoffice/CommunityServer/data/certs/dhparam.pem;

    large_client_header_buffers 4 16k;


    location / {
        proxy_pass      http://127.0.0.1:6080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    client_max_body_size 0;
}
```

I dont know if this is the best way, but it wors right now. And it is the first time it is...
