### ISSUE TITLE
Is --privileged flag now required?

### ISSUE THREAD

**Issue by N3tFX** [ONLYOFFICE/Docker-CommunityServer#116]
I am trying to install the newer docker versions of Community Server for months now with no success. But now I see something new that concerns me. In the new installation instructions found in your website: [https://helpcenter.onlyoffice.com/installation/groups-install-docker.aspx](url), I see that the new installation command is this:

`sudo docker run --net onlyoffice -i -t -d --privileged --restart=always --name onlyoffice-community-server -p 80:80 -p 443:443 -p 5222:5222`

Is the **--privileged** flag now required? Every article I've read about this flag said what a bad idea is to use it. It is considered a security risk. Please, try to avoid it if it's possible.

**Comment by Carazyda** [comment]
Hello @N3tFX yes, --privileged flag now is required. It needs to our services works well (on systemd).

**Comment by N3tFX** [comment]
Oh, no. That's sad news. If this is the final decision from the developers and can't technically be changed, we can close this issue.

**Comment by JosXa** [comment]
Effectively you are eliminating the ability to run on Docker Swarm now (as [the privileged option is not available there](https://forums.docker.com/t/privileged-containers/36935/3)). It may be deprecated, but for convenient PaaS such as [Caprover](https://caprover.com) that still rely on this functionality, running onlyoffice community is not possible anymore.

**Comment by Carazyda** [comment]
This issue was closed due to no response.
