### ISSUE TITLE
Download file failed.

### ISSUE THREAD

**Issue by xunmeng2015** [ONLYOFFICE/Docker-CommunityServer#126]
Hi I run docker without '--net' parameter, '192.168.33.3' is machine ip:

Mysql Server:
`sudo docker run -i -t -d --restart=always --name onlyoffice-mysql-server -p 5506:3306  -v /app/onlyoffice/mysql/conf.d:/etc/mysql/conf.d  -v /app/onlyoffice/mysql/data:/var/lib/mysql  -v /app/onlyoffice/mysql/initdb:/docker-entrypoint-initdb.d  -v /app/onlyoffice/mysql/logs:/var/log/mysql  -e MYSQL_ROOT_PASSWORD=onlyoffice  -e MYSQL_DATABASE=onlyoffice  mysql:5.5`

Document Server:
`sudo docker run -i -t -d -p 8085:80 --restart=always --name onlyoffice-document-server -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice  -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  -v /app/onlyoffice/DocumentServer/lib:/var/lib/onlyoffice -v /app/onlyoffice/DocumentServer/db:/var/lib/postgresql onlyoffice/documentserver`

Community Server:
`sudo docker run -i -t -d --restart=always --name onlyoffice-community-server -p 18090:443 -p 5222:5222  -e MYSQL_SERVER_ROOT_PASSWORD=onlyoffice  -e MYSQL_SERVER_DB_NAME=onlyoffice  -e MYSQL_SERVER_HOST=192.168.33.3  -e MYSQL_SERVER_PORT="5506"  -e MYSQL_SERVER_USER=onlyoffice  -e MYSQL_SERVER_PASS=onlyoffice  -e DOCUMENT_SERVER_PORT_80_TCP_ADDR=192.168.33.3:8085  -v /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data  -v /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice  onlyoffice/communityserver`

![image](https://user-images.githubusercontent.com/15134608/128120591-6dd53132-3d15-47cf-8231-c43261f58b63.png)
![image](https://user-images.githubusercontent.com/15134608/128120614-688ccd75-5cfa-4374-9ff7-6a599cecd890.png)

Do you know how to solve this issue?
Thanks.

**Comment by xunmeng2015** [comment]
I run community server in my local network, i find it is too slow when i switch menu like, so i try to change the DNS server for the docker container.
![image](https://user-images.githubusercontent.com/15134608/128123921-7a0d71f4-dd33-42c1-b03d-446e83d6291e.png)
![image](https://user-images.githubusercontent.com/15134608/128123434-76688cb0-61b9-4cde-962c-70bc12a60524.png)
Although I had already set DNS server for daemon.json, if I run with network, the DNS of container is always `127.0.0.11`. 
When i run without `--net` parameter, ths DNS server of container is the same as what i set in the daemon.json.

**Comment by xunmeng2015** [comment]
![image](https://user-images.githubusercontent.com/15134608/128140632-73aa039b-9fc5-4a11-a71a-30b74d0e18d0.png)

**Comment by Carazyda** [comment]
Hello @ xunmeng2015. You received this error because the document server container cannot resolve the community server container. This address must be specified in the portal settings on the Document Service page.

If you configured daemon.json for docker with your local dns - then you shouldn't have any problems with it. The dns inside the container is likely to change because docker uses different networks, own or host.

**Comment by xunmeng2015** [comment]
Hello @Carazyda. I don't know where to find the Document Service page. Document server or Community server?
![image](https://user-images.githubusercontent.com/15134608/128159715-06c05dbd-dd63-4504-af36-b8aab6007152.png)

Thanks.

**Comment by Carazyda** [comment]
Yes, it is. You need to specify there the address of community server, that can be resolve the document server container. Maybe `http://192.168.33.3:8090` will work.

**Comment by xunmeng2015** [comment]
![image](https://user-images.githubusercontent.com/15134608/128163261-73510743-15d9-499b-b1e3-d4cb531fc771.png)
Great! But when i specific with https address, error occured, why?

One more question, i run community server and document server in local network, but i got response very slowly, do you have any suggest to solve this problem?

**Comment by Carazyda** [comment]
There seems to be an error in the self-signed certificate, perhaps the document server needs permission in its configuration. @ShockwaveNN please take a look.

If you run docker on your local network, you need to specify local DNS servers in the docker daemon config, see our [instruction] (https://helpcenter.onlyoffice.com/installation/workspace-install-docker.aspx).

**Comment by ShockwaveNN** [comment]
There is several solution in this issue about self-signed cert

https://github.com/ONLYOFFICE/Docker-DocumentServer/issues/96

But I think it's always a bad idea to use self-signed - better use Let's Encrypt or not use it at all if it self-signed

**Comment by xunmeng2015** [comment]
Everything seems all right, Thanks!

**Comment by xunmeng2015** [comment]
Hello @ShockwaveNN @Carazyda . 
![image](https://user-images.githubusercontent.com/15134608/129030349-b67c0c60-517c-4c52-afa0-fb7ac4d80c74.png)
`11.111.25.152:18089` is machine ip and port, `22.231.1.56:a10072` is nginx ip and port, how can i solve this problem? Is this problem related to nginx?
