### ISSUE TITLE
Can't change "Document Editing Service Address" - got error "Api url: Service is not defined"

### ISSUE THREAD

**Issue by makhomed** [ONLYOFFICE/Docker-CommunityServer#16]
I install ONLYOFFICE Community Server integrated with Document and Mail Servers as it described on page https://github.com/ONLYOFFICE/Docker-CommunityServer#installing-onlyoffice-community-server-integrated-with-document-and-mail-servers

But I can't edit documents online - I got error "ONLYOFFICE™ is not available. Please contact us at support@onlyoffice.com", HTML page contains link ```<script language="javascript" type="text/javascript" src="/OfficeWeb/apps/api/documents/api.js"></script>``` but uri /OfficeWeb/apps/api/documents/api.js not exists, Firefox return error ```The page isn’t redirecting properly. Firefox has detected that the server is redirecting the request for this address in a way that will never complete.```

Next I go to settings page "Document Service Location" and try to fix "Document Editing Service Address". Old value is "/OfficeWeb/apps/api/documents/api.js", I try to enter https://onlyoffice-document-server/web-apps/apps/api/documents/api.js because onlyoffice-document-server is hostname of DocumentServer docker container and https://onlyoffice-document-server/web-apps/apps/api/documents/api.js is valid url - this url contains javascript without 301 redirects. Document Server container is up and running.

But I can't change "Document Editing Service Address" - I got error "Api url: Service is not defined" when pressing "Save" button is "Document Service Location" settings page.

What I am doing wrong, and how I can install ONLYOFFICE Community Server integrated with Document and Mail Servers as Docker containers? I do all install by instruction https://github.com/ONLYOFFICE/Docker-CommunityServer#installing-onlyoffice-community-server-integrated-with-document-and-mail-servers but I can't got working integration between community server and document server...

Or this is obsoleted instruction and installation/integration should be done in other way?

**Comment by ibnpetr** [comment]
Please specify your OS and version of the docker.
Did you use installation script when installing the product or did you create the containers manually?
Make sure that the network "onlyoffice" has been created

**Comment by makhomed** [comment]
> Please specify your OS and version of the docker.

OS: ```CentOS Linux release 7.3.1611 (Core)```
Docker: ```docker-1.12.5-14.el7.centos.x86_64```

> Did you use installation script when installing the product or did you create the containers manually?

I create containers manually by instruction https://github.com/ONLYOFFICE/Docker-CommunityServer#installing-onlyoffice-community-server-integrated-with-document-and-mail-servers

```bash
docker network create --driver bridge onlyoffice

sudo docker run --net onlyoffice -i -t -d --restart=always --name onlyoffice-document-server \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data \
    -v /app/onlyoffice/DocumentServer/logs:/var/log/onlyoffice \
    onlyoffice/documentserver

sudo docker run --net onlyoffice --privileged -i -t -d --restart=always --name onlyoffice-mail-server \
    -p 25:25 -p 143:143 -p 587:587 \
    -v /app/onlyoffice/MailServer/data:/var/vmail \
    -v /app/onlyoffice/MailServer/data/certs:/etc/pki/tls/mailserver \
    -v /app/onlyoffice/MailServer/logs:/var/log \
    -v /app/onlyoffice/MailServer/mysql:/var/lib/mysql \
    -h office.webex24.eu \
    onlyoffice/mailserver

sudo docker run --net onlyoffice -i -t -d --restart=always --name onlyoffice-community-server \
    -p 80:80 -p 5222:5222 -p 443:443 \
    -v /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data \
    -v /app/onlyoffice/CommunityServer/mysql:/var/lib/mysql \
    -v /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice \
    -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/DocumentServerData \
    -e DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server \
    -e MAIL_SERVER_DB_HOST=onlyoffice-mail-server \
    onlyoffice/communityserver
```

> Make sure that the network "onlyoffice" has been created

It created:

```
# docker network list
NETWORK ID          NAME                DRIVER              SCOPE
4053d7292c4a        bridge              bridge              local
6ed445aedbf8        host                host                local
a143ac21246b        none                null                local
484c49d0f5af        onlyoffice          bridge              local
```

P.S. when I run **in community server container** command 
```curl -Ik https://onlyoffice-document-server/OfficeWeb/apps/api/documents/api.js```
I got redirect to ```https://onlyoffice-document-server/2017-01-13-09-35/web-apps/apps/api/documents/api.js``` - this is requested javascript, Content-Type: application/x-javascript, Content-Length: 25123,
But any of these uri I can't enter in community server gui - i got error "Api url: Service is not defined".

"Document Editing Service Address" contains ```/OfficeWeb/apps/api/documents/api.js```, and request
in community server container to uri ```https://onlyoffice-community-server/OfficeWeb/apps/api/documents/api.js``` return http redirect back to this uri.

**Comment by JohnPerkin** [comment]
Hello!
The most convenient and faultless way to install ONLYOFFICE is to run installation script. The instruction you may see in our [helpcenter](http://helpcenter.onlyoffice.com/server/docker/opensource/opensource-script-installation.aspx#RunWithMail). Please try performing it.
Thank you for the interest in our product.

**Comment by makhomed** [comment]
> We tried to reproduce the issue but , alas, everything worked correctly.

I can reproduce issue. 

Bug appears when I install SSL certificates to document server as it described here:
https://github.com/ONLYOFFICE/Docker-DocumentServer#installation-of-the-ssl-certificates

When I remove /app/onlyoffice/DocumentServer/data/certs directory and restart docker - all works fine.

Looks like this is bug in ONLYOFFICE and/or bug in Docker-DocumentServer installation manual ?

Can you please fix this/these bug/bugs?

**Comment by JohnPerkin** [comment]
Hello!
When you use docker installation of Community Edition on one server there is no need to switch Document Server to https. You just need to install sertificates in Community Server. The detailed instruction you may see [here](https://github.com/ONLYOFFICE/Docker-CommunityServer#running-onlyoffice-community-server-using-https).

**Comment by makhomed** [comment]
> When you use docker installation of Community Edition on one server there is no need to switch Document Server to https. You just need to install sertificates in Community Server.

Already I know it. But if by mistake I install SSL certificates to Document Server container - I got very obscure error message when try to edit document online: "ONLYOFFICE™ is not available. Please contact us at support@onlyoffice.com".

Error message in this case can be more meaningful.

Can you fix it?
