### ISSUE TITLE
Unable to create new email domain - internal server error. Compose method.

### ISSUE THREAD

**Issue by aaronouthier** [ONLYOFFICE/Docker-CommunityServer#165]
So on step 2 of the domain wizard, it says to create an MX record pointing level 0 to “.”, which I know is incorrect. It should show the domain name.

In step 4, when I click finish, I am told “internal server error”.

I investigated the issue, and noticed none of the containers seem to have DNS resolution. /etc/resolv.conf in the mail container has DNS pointing to loopback, however, there is no process listening there. I suspect the same in the other containers. I highly suspect this is related to the server error mentioned above.

**Comment by Carazyda** [comment]
Hello @aaronouthier Please try to restart mail server container `sudo docker restart onlyoffice-mail-server`, and try again.

**Comment by aaronouthier** [comment]
Ok, so restarting mail server did cause dns to start working.

However, I still am having the same symptoms with creating a new domain.

Looking at the logs, it appears there is an authentication issue between mail server and mysql server.

From the mail server logs: `ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client ` appears a few times.

Another line reads: `Waiting for external MySql response`.

I am going to see if I can update mysql client safely.

**Comment by aaronouthier** [comment]
I am not able to do anything with the mail server as far as updates, as it is based on CentOS 6, which is now obsolete.

Have the devs been able to confirm this as a bug or reproduce the issue on your end?

If not, it could be user error. If so, then what are my options to troubleshoot?

**Comment by Carazyda** [comment]
Please check the table `mail_server_server` in the database, column `mx_record`, if your domain is there. If not, try adding.

**Comment by aaronouthier** [comment]
Unfortunately, I know almost nothing about using databases, and have not the skills to do as requested.

**Comment by aaronouthier** [comment]
After 2 hours, I was able to figure out how to show the columns in that database table.
`Field   Type    Null    Key     Default Extra
id      int     NO      PRI     NULL    auto_increment
mx_record       varchar(128)    NO
connection_string       text    NO              NULL
server_type     int     NO      MUL     NULL
smtp_settings_id        int     NO              NULL
imap_settings_id        int     NO              NULL `

**Comment by Carazyda** [comment]
It looks like something went wrong during the installation process and your mail server is missing a connection string. Try reconnecting the mail server in the portal settings(/Management.aspx?type=20) by specifying its IP address (you can check it through the `docker inspect onlyoffice-mail-server`).

**Comment by aaronouthier** [comment]
So, I have now started over from scratch, by reinstalling the OS on the entire machine. It has been about 8 hours now, but OnlyOffice is still setting up “The portal start up process might take some time, please wait”.

I am noticing in the mail server logs `docker-compose logs onlyoffice-mail-server` that I am getting authentication errors connecting to the mysql server, as I noted previously.

> Attaching to onlyoffice-mail-server
onlyoffice-mail-server         | [ INFO ] Checking configuration file: /usr/src/iRedMail/config ... [FOUND]
onlyoffice-mail-server         | [ INFO ] Import installation process status from file: /usr/src/iRedMail/runtime/install.status.
onlyoffice-mail-server         | Waiting for external MySql response
onlyoffice-mail-server         | 
onlyoffice-mail-server         | 
onlyoffice-mail-server         | 
onlyoffice-mail-server         | 
onlyoffice-mail-server         | ********************************************************************
onlyoffice-mail-server         | * Start iRedMail Configurations
onlyoffice-mail-server         | ********************************************************************
onlyoffice-mail-server         | [ INFO ] Create required system accounts: vmail, iredapd.
onlyoffice-mail-server         | [ INFO ] Configure Apache web server and PHP.
onlyoffice-mail-server         | [ INFO ] Configure PHP.
onlyoffice-mail-server         | [ INFO ] Configure MySQL database server.
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | [ INFO ] Configure Postfix (Message Transfer Agent).
onlyoffice-mail-server         | [ INFO ] Configure Cluebringer (postfix policy server).
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | [ INFO ] Configure Dovecot (pop3/imap/managesieve server).
onlyoffice-mail-server         | [ INFO ] Configure ClamAV (anti-virus toolkit).
onlyoffice-mail-server         | [ INFO ] Configure Amavisd-new (interface between MTA and content checkers).
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | [ INFO ] Configure SpamAssassin (content-based spam filter).
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | [ INFO ] Configure OpenDkim.
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | [ INFO ] Configure Fail2ban (authentication failure monitor).
onlyoffice-mail-server         | [ INFO ] Configure Server API.
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | rake aborted!
onlyoffice-mail-server         | Mysql2::Error: Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `connect'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/mysql2-0.3.21/lib/mysql2/client.rb:70:in `initialize'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/model_schema.rb:229:in `columns'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/schema_plus-1.5.3/lib/schema_plus/active_record/base.rb:23:in `columns_with_schema_plus'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/model_schema.rb:244:in `column_defaults'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/base.rb:482:in `initialize'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/persistence.rb:44:in `new'
onlyoffice-mail-server         | /usr/local/rvm/gems/ruby-2.3.3/gems/activerecord-3.2.22.5/lib/active_record/persistence.rb:44:in `create'
onlyoffice-mail-server         | /var/www/html/mailserver_api-2.0.1/Rakefile:8:in `block (2 levels) in <top (required)>'
onlyoffice-mail-server         | Tasks: TOP => api_key:generate
onlyoffice-mail-server         | (See full trace by running task with --trace)
onlyoffice-mail-server         | [ INFO ] Configure SpamTrainer.
onlyoffice-mail-server         | [ INFO ] Configure Awstats (logfile analyzer for mail and web server).
onlyoffice-mail-server         | 
onlyoffice-mail-server         | *************************************************************************
onlyoffice-mail-server         | * iRedMail-0.9.2 installation and configuration complete.
onlyoffice-mail-server         | *************************************************************************
onlyoffice-mail-server         | 
onlyoffice-mail-server         | [ INFO ] Disable SELinux in /etc/selinux/config.
onlyoffice-mail-server         | [ INFO ] Removing package(s): sendmail
onlyoffice-mail-server         | Loaded plugins: fastestmirror, ovl
onlyoffice-mail-server         | Setting up Remove Process
onlyoffice-mail-server         | Resolving Dependencies
onlyoffice-mail-server         | --> Running transaction check
onlyoffice-mail-server         | ---> Package sendmail.x86_64 0:8.14.4-9.el6_8.1 will be erased
onlyoffice-mail-server         | --> Processing Dependency: sendmail = 8.14.4-9.el6_8.1 for package: sendmail-devel-8.14.4-9.el6_8.1.x86_64
onlyoffice-mail-server         | --> Running transaction check
onlyoffice-mail-server         | ---> Package sendmail-devel.x86_64 0:8.14.4-9.el6_8.1 will be erased
onlyoffice-mail-server         | --> Finished Dependency Resolution
onlyoffice-mail-server         | 
onlyoffice-mail-server         | Dependencies Resolved
onlyoffice-mail-server         | 
onlyoffice-mail-server         | ================================================================================
onlyoffice-mail-server         |  Package               Arch          Version                 Repository    Size
onlyoffice-mail-server         | ================================================================================
onlyoffice-mail-server         | Removing:
onlyoffice-mail-server         |  sendmail              x86_64        8.14.4-9.el6_8.1        @base        1.5 M
onlyoffice-mail-server         | Removing for dependencies:
onlyoffice-mail-server         |  sendmail-devel        x86_64        8.14.4-9.el6_8.1        @base        254 k
onlyoffice-mail-server         | 
onlyoffice-mail-server         | Transaction Summary
onlyoffice-mail-server         | ================================================================================
onlyoffice-mail-server         | Remove        2 Package(s)
onlyoffice-mail-server         | 
onlyoffice-mail-server         | Installed size: 1.8 M
onlyoffice-mail-server         | Downloading Packages:
onlyoffice-mail-server         | Running rpm_check_debug
onlyoffice-mail-server         | Running Transaction Test
onlyoffice-mail-server         | Transaction Test Succeeded
onlyoffice-mail-server         | Running Transaction
onlyoffice-mail-server         | Warning: RPMDB altered outside of yum.
  Erasing    : sendmail-devel-8.14.4-9.el6_8.1.x86_64                       1/2 
  Erasing    : sendmail-8.14.4-9.el6_8.1.x86_64                             2/2 
onlyoffice-mail-server         | warning:    erase unlink of /var/log/mail/statistics failed: No such file or directory
onlyoffice-mail-server         | warning:    erase unlink of /var/log/mail failed: No such file or directory
  Verifying  : sendmail-devel-8.14.4-9.el6_8.1.x86_64                       1/2 
  Verifying  : sendmail-8.14.4-9.el6_8.1.x86_64                             2/2 
onlyoffice-mail-server         | 
onlyoffice-mail-server         | Removed:
onlyoffice-mail-server         |   sendmail.x86_64 0:8.14.4-9.el6_8.1                                            
onlyoffice-mail-server         | 
onlyoffice-mail-server         | Dependency Removed:
onlyoffice-mail-server         |   sendmail-devel.x86_64 0:8.14.4-9.el6_8.1                                      
onlyoffice-mail-server         | 
onlyoffice-mail-server         | Complete!
onlyoffice-mail-server         | [ INFO ] Copy firewall sample rules: /etc/sysconfig/iptables.
onlyoffice-mail-server         | [ INFO ] Restarting firewall ...
onlyoffice-mail-server         | [ INFO ] Copy MySQL sample file: /etc/my.cnf.
onlyoffice-mail-server         | [ INFO ] Enable SSL support for MySQL server.
onlyoffice-mail-server         | ********************************************************************
onlyoffice-mail-server         | * First mail account credential:
onlyoffice-mail-server         | *
onlyoffice-mail-server         | *   o Username: postmaster@mail.aaronouthier.com
onlyoffice-mail-server         | *   o Password: NzhhNTg4MWY1
onlyoffice-mail-server         | *
onlyoffice-mail-server         | *
onlyoffice-mail-server         | ********************************************************************
onlyoffice-mail-server         | * Congratulations, mail server setup completed successfully. Please
onlyoffice-mail-server         | * read below file for more information:
onlyoffice-mail-server         | *
onlyoffice-mail-server         | *   - /usr/src/iRedMail/iRedMail.tips
onlyoffice-mail-server         | *
onlyoffice-mail-server         | * And it's sent to your mail account postmaster@mail.aaronouthier.com.
onlyoffice-mail-server         | *
onlyoffice-mail-server         | ********************* WARNING **************************************
onlyoffice-mail-server         | Waiting for external MySql response
onlyoffice-mail-server         | [ INFO ] Configure MySQL database server.
onlyoffice-mail-server         | ERROR 1251 (08004): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         | Starting crond:           [  OK  ]
onlyoffice-mail-server         | Starting Dovecot Imap:    [  OK  ]
onlyoffice-mail-server         | Starting system logger:   [  OK  ]
onlyoffice-mail-server         | Starting amavisd:         [  OK  ]
onlyoffice-mail-server         | 
onlyoffice-mail-server         | Starting postfix:         [  OK  ]
onlyoffice-mail-server         | Starting cbpolicyd:       [  OK  ]
onlyoffice-mail-server         | Starting Clam AntiVirus Daemon: LibClamAV Warning: **************************************************
onlyoffice-mail-server         | LibClamAV Warning: ***  The virus database is older than 7 days!  ***
onlyoffice-mail-server         | LibClamAV Warning: ***   Please update it as soon as possible.    ***
onlyoffice-mail-server         | LibClamAV Warning: **************************************************
onlyoffice-mail-server         |                           [  OK  ]
onlyoffice-mail-server         | Starting clamd.amavisd: LibClamAV Warning: **************************************************
onlyoffice-mail-server         | LibClamAV Warning: ***  The virus database is older than 7 days!  ***
onlyoffice-mail-server         | LibClamAV Warning: ***   Please update it as soon as possible.    ***
onlyoffice-mail-server         | LibClamAV Warning: **************************************************
onlyoffice-mail-server         |                           [  OK  ]
onlyoffice-mail-server         | Starting httpd:           [  OK  ]
onlyoffice-mail-server         | Starting OpenDKIM Milter: opendkim: /etc/opendkim.conf: dsn:mysql://onlyoffice_mailserver_user:onlyoffice_mailserver_user_pass@onlyoffice-mysql-server/onlyoffice_mailserver/table=dkim?keycol=domain_name?datacol=id: dkimf_db_open(): Client does not support authentication protocol requested by server; consider upgrading MySQL client
onlyoffice-mail-server         |                           [FAILED]
onlyoffice-mail-server         | Starting spamd:           [  OK  ]
onlyoffice-mail-server         | Starting fail2ban:        [  OK  ]
onlyoffice-mail-server         | Starting server

**Comment by Carazyda** [comment]
Please check the status of onlyoffice-mysql-server container. If this is "restarting" - you need to redownload this repo and run docker-compose install one more time.

**Comment by aaronouthier** [comment]
All containers are “up”, none are restarting.

**Comment by Carazyda** [comment]
Ok, then please look at `docker logs onlyoffice-community-server` and `docker exec -it onlyoffice-community-server systemctl status monoserve`.

**Comment by aaronouthier** [comment]
`docker exec -it onlyoffice-community-server systemctl status monoserve`
System has not been booted with systemd as init system (PID 1). Can't operate.
`mastermind@office:/srv$ docker exec -it onlyoffice-community-server service monoserve status`
monoserve: unrecognized service

**Comment by aaronouthier** [comment]
The only errors I see in community server are:
ERROR 1146 (42S02) at line 1: Table 'onlyoffice_mailserver.greylisting_whitelist' doesn't exist
+ MAIL_SERVER_HOSTNAME=

**Comment by Carazyda** [comment]
Let's start over:

1. What host OS do you use?
2. Did you download the repository again?
3. What changes do you make to the file docker-compose.yml?
4. Show the full log of docker logs onlyoffice-community-server.

**Comment by aaronouthier** [comment]
1. Ubuntu Server 22.04 “Jammy” - no xorg, just cli.
2. I wiped the drive and reinstalled with the above OS yesterday.
3. Removed the environment variable starting with ‘$’ and replaced with the FQDN of my mail server.
4. Coming at you momentarily.

**Comment by Carazyda** [comment]
Yes, I confirm that we have a problem of running Onlyoffice with a mail server via docker-compose(bug 59041 in our private bugtracker).

**Comment by Carazyda** [comment]
Fixed by https://github.com/ONLYOFFICE/Docker-CommunityServer/commit/a35dfc7abf32093a9f20ad2127ced8825fbda10b https://github.com/ONLYOFFICE/Docker-CommunityServer/commit/bf11d95fb5eb66f3e451b6aabd637e69786d3883 https://github.com/ONLYOFFICE/Docker-CommunityServer/commit/10f15ec4d9b562027d20f0ba4c0a77300f1134b0
