### ISSUE TITLE
Failed to allocate manager object

### ISSUE THREAD

**Issue by xh542428798** [ONLYOFFICE/Docker-CommunityServer#166]
Excuse me，I run the docker compose community yml in my clean unbuntu 20.04 machine，but it wrong
How can i solve it，thank a lot.
![Screenshot_20220820-100207.png](https://user-images.githubusercontent.com/49368033/185726093-edcbaf18-d276-4bda-9c99-bffa187d1430.png)

**Comment by xh542428798** [comment]
What's more，I run the official .sh file successfully，but the same problem occured

**Comment by xh542428798** [comment]
OK, I sovled it，I reinstalled the docker-ce，and the systemd problem had been sovled

**Comment by Carazyda** [comment]
Hello @xh542428798 Glad to hear that you were able to resolve the issue.
