### ISSUE TITLE
Dokcer-compose Community server

### ISSUE THREAD

**Issue by kahlablack** [ONLYOFFICE/Docker-CommunityServer#168]
Hello, 
I migrated to Debian 11 and I used your docker compose for community server but unfortunately it does not work  
the onlyoffice-community-server container doesn't start : 

_onlyoffice/communityserver:12.0.1.1748   "/app/run-community-…"   **13 minutes ago   Up 14 seconds**   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 3306/tcp, 5280/tcp, 9865-9866/tcp, 9871/tcp, 9882/tcp, 0.0.0.0:5222->5222/tcp, :::5222->5222/tcp, 9888/tcp   onlyoffice-community-server_

script 
version: '3'
services:
  onlyoffice-mysql-server:
    container_name: onlyoffice-mysql-server
    image: mysql:8.0.29
    cap_add:
     - SYS_NICE
    environment:
     - MYSQL_ROOT_PASSWORD=*****
     - MYSQL_DATABASE=onlyoffice
     - MYSQL_USER=onlyoffice
     - MYSQL_PASS=****
    networks:
     - onlyoffice
    stdin_open: true
    tty: true
    restart: always
    volumes:
     - /app/onlyoffice/mysql/conf.d:/etc/mysql/conf.d
     - /app/onlyoffice/mysql/initdb:/docker-entrypoint-initdb.d
     - /app/onlyoffice/mysql/data:/var/lib/mysql
     - /app/onlyoffice/mysql/log:/var/log/mysql
  onlyoffice-community-server:
    container_name: onlyoffice-community-server
    image: onlyoffice/communityserver:12.0.1.1748
    depends_on:
     - onlyoffice-mysql-server
     - onlyoffice-elasticsearch
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     - CONTROL_PANEL_PORT_80_TCP=80
     - CONTROL_PANEL_PORT_80_TCP_ADDR=onlyoffice-control-panel
     - CONTROL_PANEL_PORT_443_TCP=443
     - CONTROL_PANEL_PORT_443_TCP_ADDR=onlyoffice-control-panel
     - DOCUMENT_SERVER_HOST=10.30.160.80
     - DOCUMENT_SERVER_PROTOCOL=https
     - DOCUMENT_SERVER_EXTERNAL=true 
     - MYSQL_SERVER_ROOT_PASSWORD=**
     - MYSQL_SERVER_DB_NAME=onlyoffice
     - MYSQL_SERVER_PORT=3306
     - MYSQL_SERVER_HOST=onlyoffice-mysql-server
     - MYSQL_SERVER_USER=onlyoffice
     - MYSQL_SERVER_PASS=****
     - ELASTICSEARCH_SERVER_HOST=onlyoffice-elasticsearch
     - ELASTICSEARCH_SERVER_HTTPPORT=9200
     - DOCUMENT_SERVER_JWT_ENABLED=true
     - DOCUMENT_SERVER_JWT_HEADER=**
     - DOCUMENT_SERVER_JWT_SECRET=**
    networks:
     - onlyoffice
    ports:
     - '80:80'
     - '443:443'
     - '5222:5222'
    stdin_open: true
    tty: true
    restart: always
    privileged: true
    volumes:
     - /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data
     - /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice
     - /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/DocumentServer/Data
     - /sys/fs/cgroup:/sys/fs/cgroup:rw
     - /app/onlyoffice/CommunityServer/data/certs/:/var/www/onlyoffice/Data/certs
  onlyoffice-elasticsearch:
    image: onlyoffice/elasticsearch:7.16.3
    container_name: onlyoffice-elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      - "indices.fielddata.cache.size=30%"
      - "indices.memory.index_buffer_size=30%"
      - "ingest.geoip.downloader.enabled=false"
    networks:
    - onlyoffice
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    volumes:
      - /app/onlyoffice/elasticsearch/data:/usr/share/elasticsearch/data
    expose:
      - "9200"
      - "9300"
  onlyoffice-control-panel:
    container_name: onlyoffice-control-panel
    depends_on:
     - onlyoffice-community-server
    image: onlyoffice/controlpanel:3.1.1.467
    environment:
     - ONLYOFFICE_CORE_MACHINEKEY=core_secret
     - DOCUMENT_SERVER_EXTERNAL=true
    expose:
      - '80'
      - '443'
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /app/onlyoffice/ControlPanel/data:/var/www/onlyoffice/Data
      - /app/onlyoffice/ControlPanel/logs:/var/log/onlyoffice
      - /app/onlyoffice/CommunityServer/data:/app/onlyoffice/CommunityServer/data
    networks:
      - onlyoffice
    stdin_open: true
    tty: true
networks:
  onlyoffice:
    name: onlyoffice
    driver: 'bridge'

logs : 

+ '[' -f /var/www/onlyoffice/Data/certs/onlyoffice.crt -a -f /var/www/onlyoffice/Data/certs/onlyoffice.key ']'
+ cp /etc/nginx/includes/onlyoffice-communityserver-common.conf.template /app/config/nginx/prepare-onlyoffice
+ sed -i 1d /etc/logrotate.d/nginx
+ sed '1 i\/var/log/nginx/*.log /var/log/onlyoffice/nginx.*.log {' -i /etc/logrotate.d/nginx
+ '[' 172.23.0.0/16 ']'
+ sed 's,{{DOCKER_APP_SUBNET}},172.23.0.0/16,' -i /app/config/nginx/prepare-onlyoffice
+ '[' ']'
+ '[' true == true ']'
+ sed '/files\.docservice\.secret/s!\(value\s*=\s*\"\)[^\"]*\"!\1XhvVHg5z59Z3hEXd\"!' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ sed '/files\.docservice\.secret.header/s!\(value\s*=\s*\"\)[^\"]*\"!\1Authorization\"!' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ sed '/files\.docservice\.secret/s!\(value\s*=\s*\"\)[^\"]*\"!\1XhvVHg5z59Z3hEXd\"!' -i /var/www/onlyoffice/Services/TeamLabSvc/TeamLabSvc.exe.config
+ sed '/files\.docservice\.secret.header/s!\(value\s*=\s*\"\)[^\"]*\"!\1Authorization\"!' -i /var/www/onlyoffice/Services/TeamLabSvc/TeamLabSvc.exe.config
+ '[' true == true ']'
+ cp /etc/nginx/includes/onlyoffice-communityserver-proxy-to-documentserver.conf.template /etc/nginx/includes/onlyoffice-communityserver-proxy-to-documentserver.conf
+ sed 's,{{DOCUMENT_SERVER_HOST_ADDR}},https:\/\/10.30.160.80,' -i /etc/nginx/includes/onlyoffice-communityserver-proxy-to-documentserver.conf
+ sed '/files\.docservice\.url\.internal/s!\(value\s*=\s*\"\)[^\"]*\"!\1https:\/\/10.30.160.80\/\"!' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ sed '/files\.docservice\.url\.public/s!\(value\s*=\s*\"\)[^\"]*\"!\1https:\/\/10.30.160.80\/\"!' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ sed '/files\.docservice\.url\.internal/s!\(value\s*=\s*\"\)[^\"]*\"!\1https:\/\/10.30.160.80\/\"!' -i /var/www/onlyoffice/Services/TeamLabSvc/TeamLabSvc.exe.config
+ sed '/files\.docservice\.url\.public/s!\(value\s*=\s*\"\)[^\"]*\"!\1https:\/\/10.30.160.80\/\"!' -i /var/www/onlyoffice/Services/TeamLabSvc/TeamLabSvc.exe.config
+ '[' -n 172.23.0.0/16 ']'
+ '[' -n '' ']'
+ '[' false == true ']'
+ '[' false == true ']'
+ '[' true == true ']'
+ cp /etc/nginx/includes/onlyoffice-communityserver-proxy-to-controlpanel.conf.template /etc/nginx/includes/onlyoffice-communityserver-proxy-to-controlpanel.conf
+ sed 's,{{CONTROL_PANEL_HOST_ADDR}},onlyoffice-control-panel,' -i /etc/nginx/includes/onlyoffice-communityserver-proxy-to-controlpanel.conf
+ sed 's,{{SERVICE_SSO_AUTH_HOST_ADDR}},onlyoffice-control-panel,' -i /etc/nginx/includes/onlyoffice-communityserver-proxy-to-controlpanel.conf
+ sed '/web\.controlpanel\.url/s/\(value\s*=\s*\"\)[^\"]*\"/\1\/controlpanel\/\"/' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ sed '/web\.controlpanel\.url/s/\(value\s*=\s*\"\)[^\"]*\"/\1\/controlpanel\/\"/' -i /var/www/onlyoffice/Services/TeamLabSvc/TeamLabSvc.exe.config
+ '[' SERVER == SERVER ']'
++ seq 1 1
+ for serverID in $(seq 1 ${APP_MONOSERVE_COUNT})
+ '[' 1 == 1 ']'
+ sed '/web.warmup.count/s/value=\"\S*\"/value=\"1\"/g' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ sed '/web.warmup.domain/s/value=\"\S*\"/value=\"localhost\/warmup\"/g' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ sed '/core.machinekey/s!value=".*"!value="core_secret"!g' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ sed '/core.machinekey/s!value=".*"!value="core_secret"!g' -i /var/www/onlyoffice/ApiSystem/Web.config
+ sed '/core.machinekey/s!value=".*"!value="core_secret"!g' -i /var/www/onlyoffice/Services/TeamLabSvc/TeamLabSvc.exe.config
+ sed '/core\.machinekey/s!"core\.machinekey".*!"core\.machinekey":"core_secret",!' -i /var/www/onlyoffice/Services/ASC.Socket.IO/config/config.json
+ sed 's!machine_key\s*=.*!machine_key = core_secret!g' -i /var/www/onlyoffice/Services/TeamLabSvc/radicale.config
+ sed 's!"core\.machinekey":.*,!"core\.machinekey":"core_secret",!g' -i /var/www/onlyoffice/Services/ASC.UrlShortener/config/config.json
+ sed 's!"machinekey":.*!"machinekey":"core_secret",!' -i /etc/onlyoffice/communityserver/appsettings.production.json
+ continue
+ sed 's/{{APP_NIGNX_KEEPLIVE}}/32/g' -i /app/config/nginx/prepare-onlyoffice
+ bash -c 'echo "onlyoffice ALL=(ALL) NOPASSWD: /usr/sbin/service" | (EDITOR="tee -a" visudo)'
onlyoffice ALL=(ALL) NOPASSWD: /usr/sbin/service
+ '[' false == true ']'
+ systemctl enable redis-server.service
Synchronizing state of redis-server.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable redis-server
Created symlink /etc/systemd/system/redis.service → /lib/systemd/system/redis-server.service.
+ service redis-server start
Starting redis-server: redis-server.
+ redis-cli config set save ''
OK
+ redis-cli config rewrite
OK
+ redis-cli flushall
OK
+ service redis-server stop
Stopping redis-server: redis-server.
+ '[' SERVER == SERVICES ']'
+ systemctl enable monoserveApiSystem.service
++ seq 1 1
+ for serverID in $(seq 1 ${APP_MONOSERVE_COUNT})
+ index=1
+ '[' 1 == 1 ']'
+ index=
+ systemctl enable monoserve.service
+ chown -R onlyoffice:onlyoffice /var/log/onlyoffice
+ chown -R onlyoffice:onlyoffice /var/www/onlyoffice/DocumentServerData
++ ls -alhd /var/www/onlyoffice/Data
++ awk '{ print $3 }'
+ '[' onlyoffice '!=' onlyoffice ']'
+ '[' '!' -d /var/www/onlyoffice/Data/Index/v7.16.3 ']'
+ mysql_scalar_exec 'TRUNCATE webstudio_index'
+ local queryResult=
+ '[' '' == opt_ignore_db_name ']'
++ mysql --silent --skip-column-names -h onlyoffice-mysql-server -P 3306 -u onlyoffice --password=Vjkcs477jiEpq25V -D onlyoffice -e 'TRUNCATE webstudio_index'
mysql: [Warning] Using a password on the command line interface can be insecure.
+ queryResult=
+ echo

+ mkdir -p /var/log/onlyoffice//Index
+ mkdir -p /var/www/onlyoffice/Data/Index/v7.16.3
++ ls -alhd /var/www/onlyoffice/Data/Index/v7.16.3
++ awk '{ print $3 }'
+ '[' root '!=' elasticsearch ']'
+ chown -R elasticsearch:elasticsearch /var/www/onlyoffice/Data/Index/v7.16.3
+ chown -R elasticsearch:elasticsearch /var/log/onlyoffice//Index
+ grep -q onlyoffice-xmppserver
+ dpkg -l
+ sed '/web\.talk/s/value=\"\S*\"/value=\"true\"/g' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ sed '/web\.chat/s/value=\"\S*\"/value=\"false\"/g' -i /var/www/onlyoffice/WebStudio/web.appsettings.config
+ systemctl stop onlyofficeRadicale
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeTelegram
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeSocketIO
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeThumb
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeFeed
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeIndex
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeJabber
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeMailAggregator
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeMailWatchdog
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeMailCleaner
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeMailImap
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeNotify
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeBackup
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeStorageMigrate
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeStorageEncryption
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeUrlShortener
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeThumbnailBuilder
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop onlyofficeAutoCleanUp
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop god
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl enable god
+ systemctl stop elasticsearch
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop redis-server
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop mysql
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop nginx
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl stop monoserveApiSystem.service
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl enable monoserveApiSystem.service
++ seq 1 1
+ for serverID in $(seq 1 ${APP_MONOSERVE_COUNT})
+ index=1
+ '[' 1 == 1 ']'
+ index=
+ systemctl stop monoserve.service
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl enable monoserve.service
+ '[' false == true ']'
+ systemctl enable onlyofficeRadicale.service
+ systemctl enable onlyofficeTelegram.service
+ systemctl enable onlyofficeSocketIO.service
+ systemctl enable onlyofficeThumb.service
+ systemctl enable onlyofficeFeed.service
+ systemctl enable onlyofficeIndex.service
+ systemctl enable onlyofficeJabber.service
+ systemctl enable onlyofficeMailAggregator.service
+ systemctl enable onlyofficeMailWatchdog.service
+ systemctl enable onlyofficeMailCleaner.service
+ systemctl enable onlyofficeMailImap.service
+ systemctl enable onlyofficeNotify.service
+ systemctl enable onlyofficeBackup.service
+ systemctl enable onlyofficeStorageMigrate.service
+ systemctl enable onlyofficeStorageEncryption.service
+ systemctl enable onlyofficeUrlShortener.service
+ systemctl enable onlyofficeThumbnailBuilder.service
+ systemctl enable onlyofficeAutoCleanUp.service
+ '[' SERVER == SERVER ']'
+ mv /app/config/nginx/prepare-onlyoffice /etc/nginx/sites-enabled/onlyoffice
+ service nginx stop
+ systemctl enable nginx.service
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
++ grep -v grep
++ awk '{print $2}'
++ grep cron
++ ps auxf
+ PID=
+ '[' onlyoffice-elasticsearch ']'
+ service elasticsearch stop
 * Stopping Elasticsearch Server                                         [ OK ] 
+ systemctl disable elasticsearch.service
Synchronizing state of elasticsearch.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable elasticsearch
+ rm -f /usr/lib/systemd/system/elasticsearch.service
+ rm -f /etc/init.d/elasticsearch
+ '[' -n '' ']'
+ rm -dfr '/tmp/onlyoffice*'
+ rm -dfr '/var/run/onlyoffice/*'
+ rm -dfr '/var/cache/nginx/onlyoffice/*'

**+ '[' false == true ']'**
I don't understand why the last parameter of the script /app/run-community-server.sh is set to false.

**Comment by Carazyda** [comment]
Hello @kahlablack yes, we have a problem with docker-compose on Ubuntu 22.04 and Debian 11 (Bug 58578 in our private bugtracker). But you can try use this solution https://github.com/ONLYOFFICE/CommunityServer/issues/424#issuecomment-1231672641.

**Comment by VincentSC** [comment]
Ok, I've tried https://github.com/gdraheim/docker-systemctl-replacement to fix this, as the ~~solution~~ workaround does not work. It does not give the errors anymore, but it gives these instead:
```
onlyoffice-community-server    | ERROR:systemctl: dbus-org.freedesktop.resolve1.service: Executable path is not absolute, ignoring: !!/lib/systemd/systemd-resolved
onlyoffice-community-server    | ERROR:systemctl: systemd-networkd.service: Executable path is not absolute, ignoring: !!/lib/systemd/systemd-networkd
onlyoffice-community-server    | ERROR:systemctl: systemd-resolved.service: Executable path is not absolute, ignoring: !!/lib/systemd/systemd-resolved
onlyoffice-community-server    | ERROR:systemctl: systemd-timesyncd.service: Executable path is not absolute, ignoring: !!/lib/systemd/systemd-timesyncd
```

For the idea of it, I added git and python3 to apt, and then added this to after the last apt install:
```
RUN git clone https://github.com/gdraheim/docker-systemctl-replacement /opt/systemctl-github && \
    rm -f /bin/systemctl && \
    ln -s /opt/systemctl-github/files/docker/systemctl.py /bin/systemctl
```

Unfortunately this is not working. I suspect the problem is somewhere else.

As the scripts (Dockerfile and run-community-server.sh) are simply bad (using hammers to fix non-understood parts of Linux/Docker, and no documentation), I have no idea what is really the goal, and thus where to start fixing. Sorry.

Also, the used libraries are years and years old, and that adds to the serious security problem caused by the privileged mode. Private mode for cgroupns is a feature you really want here! Especially because you only use it for starting some services that should have been external.

IMO it needs a full rewrite. Is there a design plan for what this docker should do?

**Comment by ovizii** [comment]
I'm also very disappointed and totally agree with VincentSC. Additionally, I found this info on their docs page:

`Temporarily does not work on Ubuntu 22.04 and Debian 11.`

Not quite sure if there is any progress on this issue to produce a properly working docker-compose.yml for any OS.

**Comment by VincentSC** [comment]
If it would work on 22.10 or 23.04 then I'd be happy. :)

**Comment by sanyaade-teachings** [comment]
I am same issues, just installed the Docker compose but it is eaten up all the memory, swap space, etc...
Same memory issues running the workspace docker compose edition.
Every installs and running on a Server with **64GB RAM**, **ITB HDD** on a bare-bone Ubuntu 24.04 Server. 
The Hardware has 4 socket x 16 core (64 core) **Dell R815**
No user apart from the initial Administrator created.

See below:
![image](https://github.com/user-attachments/assets/eac84e47-799e-45f1-bf16-385b5e571c15)

Swap space has been eaten up as well

Please help! Any suggestion, please? 
Many thanks!

God blesses!!!

Regards

**Comment by Carazyda** [comment]
Hello @sanyaade-teachings In this thread we are discussing docker compose method installation errors on ubuntu 22.04/debian11. Please open a new issue with more details. Please provide your yml file, `free -m` command output and htop screenshot sorted by memory.

**Comment by ovizii** [comment]
I see this issue has been closed. Would somebody please sum up the outcome as I do not find any results in this thread.
