### ISSUE TITLE
nginx log files not rotated by logrotate, they grow unlimited in size.

### ISSUE THREAD

**Issue by makhomed** [ONLYOFFICE/Docker-CommunityServer#17]
nginx log files not rotated by logrotate, they grow unlimited in size.

/etc/logrotate.d/nginx only watch nginx files by mask /var/log/nginx/*.log
but actually ONLYOFFICE nginx log files located in dir /var/log/onlyoffice,
nginx.access.log, nginx.error.log, nginx.apisystem.access.log, nginx.apisystem.error.log

you should move nginx log files to currently empty dir /var/log/onlyoffice/nginx
and add mask /var/log/onlyoffice/nginx/*.log to file /etc/logrotate.d/nginx:

```diff
# diff -u /etc/logrotate.d/nginx.old /etc/logrotate.d/nginx
--- /etc/logrotate.d/nginx.old  2016-12-27 14:45:35.000000000 +0000
+++ /etc/logrotate.d/nginx      2017-03-22 18:58:19.054000000 +0000
@@ -1,4 +1,4 @@
-/var/log/nginx/*.log {
+/var/log/nginx/*.log /var/log/onlyoffice/nginx/*.log {
         daily
         missingok
         rotate 52
```
hope this help, and you can reproduce and fix this BUG with unlimited size of nginx log files?

**Comment by JohnPerkin** [comment]
We will take your suggestion into consideration. Thank you for the attention to ONLYOFFICE.
