### ISSUE TITLE
the SQL script can not match the mysql's version of 8.0

### ISSUE THREAD

**Issue by starshowing** [ONLYOFFICE/Docker-CommunityServer#171]
the SQL script  can run in the version of 5,7,not match the version of 8.0.
The follow can be fixed.
CREATE USER 'onlyoffice_user'@'localhost' IDENTIFIED BY 'onlyoffice_pass';
CREATE USER 'onlyoffice_user'@'%' IDENTIFIED BY 'onlyoffice_pass';
CREATE USER 'mail_admin'@'localhost' IDENTIFIED BY 'Isadmin123';
CREATE USER 'mail_admin'@'%' IDENTIFIED BY 'Isadmin123';
GRANT ALL PRIVILEGES ON * . * TO 'root'@'%';
GRANT ALL PRIVILEGES ON * . * TO 'onlyoffice_user'@'localhost';
GRANT ALL PRIVILEGES ON * . * TO 'onlyoffice_user'@'%';
GRANT ALL PRIVILEGES ON * . * TO 'mail_admin'@'%';
GRANT ALL PRIVILEGES ON * . * TO 'mail_admin'@'localhost';
FLUSH PRIVILEGES;

**Comment by Carazyda** [comment]
Hello @starshowing By default we use MySQL v8.0.29 in our docker installation. Please describe in more details what problem you are facing?

**Comment by starshowing** [comment]
when i use the followed script, the mysql can not run. Because the SQL script can run in the version of 5,7,not match the version of 8.0.
![image](https://user-images.githubusercontent.com/16507078/204182174-a95b4188-dce8-4005-89aa-5ab69cfaf56a.png)

![image](https://user-images.githubusercontent.com/16507078/204182468-a5dd49ae-c009-45cb-8044-ac8524f9d800.png)

**Comment by Carazyda** [comment]
Yes, I can confirm that the mysql container fails to start with the error:
`[ERROR] [MY-010187] [Server] Could not open file '/var/log/mysql/error.log' for error logging: Permission denied`

We will fix this soon.

**Comment by Carazyda** [comment]
Fixed by https://github.com/ONLYOFFICE/Docker-CommunityServer/commit/10f15ec4d9b562027d20f0ba4c0a77300f1134b0
