### ISSUE TITLE
Failed to allocate manager object, freezing

### ISSUE THREAD

**Issue by jiayouchongmingniao** [ONLYOFFICE/Docker-CommunityServer#172]
docker pull onlyoffice/communityserver:12.1.0.1760
docker start with error, would you please help check and give some clue to solve. many thanks !

+ systemctl enable monoserveApiSystem.service
++ seq 1 1
+ for serverID in $(seq 1 ${APP_MONOSERVE_COUNT})
+ index=1
+ '[' 1 == 1 ']'
+ index=
+ systemctl stop monoserve.service
System has not been booted with systemd as init system (PID 1). Can't operate.
+ systemctl enable monoserve.service
+ '[' false == true ']'
+ systemctl enable onlyofficeRadicale.service
+ systemctl enable onlyofficeTelegram.service
+ systemctl enable onlyofficeSocketIO.service
+ systemctl enable onlyofficeThumb.service
+ systemctl enable onlyofficeFeed.service
+ systemctl enable onlyofficeIndex.service
+ systemctl enable onlyofficeJabber.service
+ systemctl enable onlyofficeMailAggregator.service
+ systemctl enable onlyofficeMailWatchdog.service
+ systemctl enable onlyofficeMailCleaner.service
+ systemctl enable onlyofficeMailImap.service
+ systemctl enable onlyofficeNotify.service
+ systemctl enable onlyofficeBackup.service
+ systemctl enable onlyofficeStorageMigrate.service
+ systemctl enable onlyofficeStorageEncryption.service
+ systemctl enable onlyofficeUrlShortener.service
+ systemctl enable onlyofficeThumbnailBuilder.service
+ systemctl enable onlyofficeAutoCleanUp.service
+ '[' SERVER == SERVER ']'
+ mv /app/config/nginx/prepare-onlyoffice /etc/nginx/sites-enabled/onlyoffice
+ service nginx stop
+ systemctl enable nginx.service
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
++ grep cron
++ grep -v grep
++ awk '{print $2}'
++ ps auxf
+ PID=
+ '[' onlyoffice-elasticsearch ']'
+ service elasticsearch stop
 * Stopping Elasticsearch Server                                         [ OK ]
+ systemctl disable elasticsearch.service
Synchronizing state of elasticsearch.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable elasticsearch
+ rm -f /usr/lib/systemd/system/elasticsearch.service
+ rm -f /etc/init.d/elasticsearch
+ '[' -n '' ']'
+ rm -dfr '/tmp/onlyoffice*'
+ rm -dfr '/var/run/onlyoffice/*'
+ rm -dfr '/var/cache/nginx/onlyoffice/*'
+ '[' true == true ']'
+ exec /lib/systemd/systemd
[!!!!!!] Failed to allocate manager object, freezing.

**Comment by Carazyda** [comment]
Hello @jiayouchongmingniao you need add this parameter to docker run command.
`-v /sys/fs/cgroup:/sys/fs/cgroup:rw`

**Comment by jiayouchongmingniao** [comment]
solved！thanks ！

modified from relative path to absolute path
-v ./sys/fs/cgroup:/sys/fs/cgroup:rw
to
-v /sys/fs/cgroup:/sys/fs/cgroup:rw
