### ISSUE TITLE
Can you provide a YAML file that only uses HTTP and does not use HTTPS or JWT?

### ISSUE THREAD

**Issue by hyhse** [ONLYOFFICE/Docker-CommunityServer#185]
After installing Docker Compose, I tried to access 0.0.0.0:80 but the status showed that TLS handshake was in progress.

Distributor ID:	Openkylin
Description:	openKylin 0.9.5
Release:	0.9.5
Docker version 20.10.16, build 20.10.16-ok1

**Comment by hyhse** [comment]
look like same with 
[Problem with onlyoffice-community-server trying to get it running via docker-compose #175](https://github.com/ONLYOFFICE/Docker-CommunityServer/issues/175)

**Comment by ovizii** [comment]
Would you mind sharing how you sorted this out?
