### ISSUE TITLE
Server not found after login

### ISSUE THREAD

**Issue by Libeccio84** [ONLYOFFICE/Docker-CommunityServer#19]
I have recently installed Onlyoffice community server according to [this](http://helpcenter.onlyoffice.com/server/docker/opensource/opensource-script-installation.aspx?_ga=2.83144534.1702585237.1494430378-1027215106.1489483677) guide.
The installation run smoothly and docker containers are up and running, but this is what I get right after, as I try to enter the community server:
![screen shot 2017-05-10 at 17 54 23](https://cloud.githubusercontent.com/assets/23318355/25908419/725128b4-35aa-11e7-8dc7-76473fb5740d.png)

Additional info:
- docker installed under CentOS
- selinux and firewall are disabled in the docker host
- nginx is running in the container
- this is the error log
```
2017/05/10 15:58:29 [crit] 51#51: *1 connect() to unix:/var/run/onlyoffice/onlyoffice.socket failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "HEAD /warmup/auth.aspx HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice.socket:", host: "localhost"

2017/05/10 15:58:31 [crit] 51#51: *3 connect() to unix:/var/run/onlyoffice/onlyoffice2.socket failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: , request: "HEAD /warmup2/auth.aspx HTTP/1.1", upstream: "fastcgi://unix:/var/run/onlyoffice/onlyoffice2.socket:", host: "localhost"

2017/05/10 15:59:21 [warn] 49#49: duplicate MIME type "text/html" in /etc/nginx/includes/onlyoffice-communityserver-common.conf:19
```
- files /var/run/onlyoffice/onlyoffice.socket and /var/run/onlyoffice/onlyoffice2.socket exist in the container

Can anyone help me?

**Comment by JohnPerkin** [comment]
Hello @Libeccio84!
We tried to reproduce the issue but everything worked well. The reason may be in your network configuration.
