### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate.

### ISSUE THREAD

**Issue by Justman10000** [ONLYOFFICE/Docker-CommunityServer#196]
Have above error always! Is probably because **systemctl** is used instead of **service**

**Comment by Justman10000** [comment]
@evgeniy-antonyuk

**Comment by Carazyda** [comment]
Hello @Justman10000 Please describe in more detail how did you install Onlyoffice Workspace?

**Comment by Justman10000** [comment]
> Hello @Justman10000 Please describe in more detail how did you install Onlyoffice Workspace?

Via Docker Image

**Comment by Carazyda** [comment]
Are you using our install script, docker-compose or docker run command?

**Comment by Justman10000** [comment]
> Are you using our install script, docker-compose or docker run command?

docker run

**Comment by Carazyda** [comment]
Are there any errors when opening the portal on the web? Can you provide the full docker run command? And what OS host are you using?

**Comment by Justman10000** [comment]
> Are there any errors when opening the portal on the web?
?

> Can you provide the full docker run command?
[Here](https://pastebin.com/e4eDKY8f)

> And what OS host are you using?
Linux Debian 11

**Comment by Carazyda** [comment]
You need to add the `--cgroupns=host` parameter in docker run. Also please change `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` to `-v /sys/fs/cgroup:/sys/fs/cgroup:rw`. This is described in our [readme](https://github.com/ONLYOFFICE/Docker-CommunityServer#installing-community-server) for this repo.

**Comment by Justman10000** [comment]
> You need to add the `--cgroupns=host` parameter in docker run. Also please change `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` to `-v /sys/fs/cgroup:/sys/fs/cgroup:rw`. This is described in our [readme](https://github.com/ONLYOFFICE/Docker-CommunityServer#installing-community-server) for this repo.

WORKING 🥳! Whatever the parameter `--cgroupns=host` changes! However, now have this:
![grafik](https://github.com/ONLYOFFICE/Docker-CommunityServer/assets/49990629/6a2a99fc-16a8-4f85-a41f-13993a6cfd8d)

Translated:
> Security token of the document is not correct
> Contact your server administrator
>
> Click OK to go to the document list

**Comment by Carazyda** [comment]
You need also add this parameters to docker run 
for community-server
`-e DOCUMENT_SERVER_JWT_ENABLED=true`
`-e DOCUMENT_SERVER_JWT_HEADER=your_header`
`-e DOCUMENT_SERVER_JWT_SECRET=your_secret`
Or
`-e DOCUMENT_SERVER_JWT_ENABLED=false`

For document-server
`-e JWT_ENABLED=true`
`-e JWT_HEADER=your_header`
`-e JWT_SECRET=your_secret`
Or
`-e JWT_ENABLED=false`

**Comment by Justman10000** [comment]
JWT_HEADER?

**Comment by Carazyda** [comment]
You can specify a random value, like AuthorizationJwt.

**Comment by Justman10000** [comment]
> You can specify a random value, like AuthorizationJwt.

Now this:
![grafik](https://github.com/ONLYOFFICE/Docker-CommunityServer/assets/49990629/ceefe812-bf27-4f2d-a2d9-4f70ad93eb14)

**Comment by Carazyda** [comment]
This error occurs most likely due to a non-standard port for running the community server. Try adding it to the community server address in the portal settings /Management.aspx?type=17.

**Comment by Justman10000** [comment]
> This error occurs most likely due to a non-standard port for running the community server. Try adding it to the community server address in the portal settings /Management.aspx?type=17.

Here?
![grafik](https://github.com/ONLYOFFICE/Docker-CommunityServer/assets/49990629/61c6bcd9-6df1-4cd6-87bc-df723028f02d)

**Comment by Carazyda** [comment]
Yes, please try change Community Server address to `http://onlyoffice-community-server:4457`.

**Comment by Justman10000** [comment]
> http://onlyoffice-community-server:4457

> Converter url: Specified value has invalid HTTP Header characters. Parameter name: name

**Comment by Justman10000** [comment]
Fixed it! `JWT_HEADER` must not contain a random value but MUST contain `AuthorizationJwt`! `http://onlyoffice-community-server/` I have to change to my IP

**Comment by Carazyda** [comment]
Glad to hear it. Feel free to open new issues if you encounter any problems.
