### ISSUE TITLE
No Webdav connections possible - always 401 Unauthorized

### ISSUE THREAD

**Issue by OXERY** [ONLYOFFICE/Docker-CommunityServer#208]
Hi there,

I recently installed an OnlyOffice Workspace instance using [the script](https://helpcenter.onlyoffice.com/installation/workspace-install-docker.aspx). Unfortunately, it seems the WebDav connection isn't allowed using this setup.

I see a logfile `web.webdav.log.02-21` under `/app/onlyoffice/CommunityServer/logs`, so I assume, that I'm right when creating an issue here. But as the logfile doesn't contain any info & there isn't anything documented how to set up more logging, Im afraid that doesn't work.

**tl;dr;** Login in webdav isn't possible with mail + pass which works in the portal - a 401 is the result.

**What I've tried:**

- Connecting via Webbrowser -> Basic Auth with my regular admin user + pass, which works in the portal
- Connecting via Ubuntu file explorer (same creds)
- Connecting via WinSCP (same creds)
- Connecting via curl (authenticated and unauthenticated)

When executing `curl -kv https://myworkspacedomain.de/webdav` I get the following result:
```
*   Trying xxx.xxx.xxx.xxx:443...
* Connected to myworkspacedomain.de (xxx.xxx.xxx.xxx) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> GET /webdav HTTP/1.1
> Host: myworkspacedomain.de
> User-Agent: curl/8.4.0
> Accept: */*
>
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 301 Moved Permanently
< Alt-Svc: h3=":443"; ma=2592000
< Content-Length: 178
< Content-Type: text/html
< Date: Wed, 21 Feb 2024 14:11:56 GMT
< Location: http://myworkspacedomain.de/webdav/
< Server: Caddy
< Server: nginx/1.18.0 (Ubuntu)
< X-Frame-Options: SAMEORIGIN
<
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
* Connection #0 to host myworkspacedomain.de left intact
```
-> As you can see, I am redirected to .../webdav/.

When following redirects, it ends in a 401 Unauthorized - with and without authentication

**Comment by OXERY** [comment]
Thx @Carazyda, as the instructions only refer to the client-part of the overall setup: Yes, I did! :)
The link you provided answers simply with an `OK`

**Comment by Carazyda** [comment]
Can you tell us in more detail how your network is structured? Is it closed or open access? How did you set up SSL? Are there any errors in web.api.log?

**Comment by OXERY** [comment]
After few hours of research, it resulted in the reverse proxy being the problem - as I'm always using Traefik I was quite wondered why that didn't work. I now switched my port forwarding to fit directly to the 443 Port of Onlyoffice and it seems to work so far.

**Comment by xionjames** [comment]
@OXERY I have exactly the same issue and I'm using Traefik as well.
Could you please tell me what exactly did you change?
Thank you.

**Comment by OXERY** [comment]
@xionjames I used the official Docker Installer and just forwarded Port 443 directly and used a VM with a separate public IP.
