### ISSUE TITLE
docker container restart fail

### ISSUE THREAD

**Issue by chicol** [ONLYOFFICE/Docker-CommunityServer#24]
OS: CentOS Linux release 7.3.1611 (Core) 
community server container restart fail.
docker continously print "Restarting nginx" from command "docker logs -f "

 * Reloading nginx nginx                                                 [ OK ] 
reload nginx config
FINISH
 * Restarting nginx nginx                                                       start-stop-daemon: warning: failed to kill 39: No such process
                                                                         [ OK ]
MAIL_SERVER_API_HOST is empty
 * Restarting nginx nginx                                                       start-stop-daemon: warning: failed to kill 39: No such process
                                                                         [ OK ]

docker ps command:
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                            PORTS                                                                                NAMES
3d0a03117f31        onlyoffice/communityserver   "/bin/sh -c 'exec ..."   6 weeks ago         Restarting (246) 16 seconds ago                                                                                        onlyoffice-community-server

**Comment by chicol** [comment]
Recreate community server container with variable "-e EXTERNAL_IP". looks no problem.

**Comment by RooyeKhat** [comment]
@chicol 
Hi
i have same problem but i not have backup
can you tell me how can recreate without lost data in oldest container 

Thanks
