### ISSUE TITLE
Cookie too large error

### ISSUE THREAD

**Issue by cuibonobo** [ONLYOFFICE/Docker-CommunityServer#28]
Bug report.

User filters and page settings appear to be saved in cookies, so users with many settings can receive a `400 - Request Header or Cookie Too Large` error when browsing the community server site. The cookie that caused this particular error is 8,220 bytes. By default, nginx is configured to limit cookies to 8 kilobytes, so this cookie is slightly larger than the default limit.

An easy fix would be to add `large_client_header_buffers 4 16k;` to the nginx server block, but that will be reset if the container is restarted.

Community Server 9.1.0.418, installed via Docker.

**Comment by alexeybannov** [comment]
Thank you. We will include this fix in the next release.
