### ISSUE TITLE
/var/run/docker.sock: no such file or directory.

### ISSUE THREAD

**Issue by jarlarntzen** [ONLYOFFICE/Docker-CommunityServer#3]
Hi.

Tried to run 
```
sudo docker run -i -t -d -p 80:80 onlyoffice/communityserver
```
Which resulted in:
```
Post http:///var/run/docker.sock/v1.20/containers/create: dial unix /var/run/docker.sock: no such file or directory.
* Are you trying to connect to a TLS-enabled daemon without TLS?
* Is your docker daemon up and running?
```

Trying this on Ubuntu 14.04 LTS

**Comment by AnaMih** [comment]
Please, check if the docker services and daemons are running. For example by the commands "service docker status" and "sudo docker -d -D".

**Comment by jarlarntzen** [comment]
Ok. "service docker start" fixed it for me

**Comment by rsangeetha** [comment]
I was getting similar error when I run the command "docker images"
2018/08/02 13:40:29 Get http:///var/run/docker.sock/v1.14/images/json: dial unix /var/run/docker.sock: no such file or directory
"service docker start" fixed it for me as well!

**Comment by BagavathiSelvam** [comment]
> 

it works..thank u

**Comment by Grechemax** [comment]
service docker start
zsh: command not found: service

any ideas?

**Comment by Carazyda** [comment]
Hello @Grechemax What host OS are you using? Please try `systemctl status docker`.

**Comment by maite-ai** [comment]
I run "service docker start" (WSL2/Ubuntu) and it throws me the following error:
`docker: unrecognized service`

I got the docker desktop running.

and the "docker info":
```
Client: Docker Engine - Community
 Version:    24.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.20.2-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.6
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scan
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  0.20.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by Carazyda** [comment]
Hi @maite-ai Your problem is not related to Onlyoffice. Try searching the web for information like [stackoverflow](https://stackoverflow.com/questions/63012885/docker-unrecounced-service).

**Comment by AlexeyInc** [comment]
On Docker Desktop for Mac this checkbox made my day 
![image](https://github.com/ONLYOFFICE/Docker-CommunityServer/assets/29926552/a47cb3f5-648d-46aa-ad51-4b22c5ebe6a5)
