### ISSUE TITLE
Issues with 'bash opensource-install.sh -u true' script (trying to expose both containers on 80 port)

### ISSUE THREAD

**Issue by kovalroma** [ONLYOFFICE/Docker-CommunityServer#33]
I need to move my Onlyoffice from one server to another

**Steps to reproduce.**
1. Copy /app folder from server A to /app folder on server B
2. On server B start bash opensource-install.sh -u true 

**Expected result.**
Running 3 containers: 

```
CONTAINER ID        IMAGE                               COMMAND                  CREATED              STATUS              PORTS                                      NAMES

6cbc2496795a        mysql:5.5                           "docker-entrypoint..."   31 seconds ago       Up 28 seconds       3306/tcp                                   onlyoffice-mysql-server

38fb09135080        onlyoffice/documentserver:4.4.3.7   "/bin/sh -c 'bash ..."   About a minute ago   Up About a minute   80->80/tcp, 0.0.0.0:443->443/tcp   onlyoffice-document-server

3c32d2d0878a        onlyoffice/communityserver:9.1.0.418   "/usr/bin/dumb-ini..."   52 seconds ago      Up 50 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 3306/tcp, 5280/tcp, 9865-9866/tcp, 9871/tcp, 9882/tcp, 0.0.0.0:5222->5222/tcp, 9888/tcp   onlyoffice-community-server
```

**Actual result.**
Running only 2 containers:

```
CONTAINER ID        IMAGE                               COMMAND                  CREATED              STATUS              PORTS                                      NAMES
6cbc2496795a        mysql:5.5                           "docker-entrypoint..."   31 seconds ago       Up 28 seconds       3306/tcp                                   onlyoffice-mysql-server

3c32d2d0878a        onlyoffice/communityserver:9.1.0.418   "/usr/bin/dumb-ini..."   52 seconds ago      Up 50 seconds       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 3306/tcp, 5280/tcp, 9865-9866/tcp, 9871/tcp, 9882/tcp, 0.0.0.0:5222->5222/tcp, 9888/tcp   onlyoffice-community-server
```

**Notes**
After trying to install onlyoffice-document-server manually by 
`bash opensource-install.sh -ics false -ids true -ims false -es true`
I've got an error `The following ports must be open: 80`

`sudo netstat -lnp | grep ':80'
tcp6       0      0 :::80                   :::*                    LISTEN      1317/docker-proxy`

It seems to me that `bash opensource-install.sh -u true` install and configure communityserver and document-server containers on the same 80 tcp port.

On my A server containers running with following exposed ports
`0.0.0.0:80->80/tcp` for communityserver
`80->80/tcp` for document server

On server B docker trying to exposed ports 
`0.0.0.0:80->80/tcp` for communityserver
`0.0.0.0:80->80/tcp` for document server

More information here
[http://dev.onlyoffice.org/ru/viewtopic.php?p=22482&sid=a26f78db713b90fba3b757ca43ea939f#p22482](http://dev.onlyoffice.org/ru/viewtopic.php?p=22482&sid=a26f78db713b90fba3b757ca43ea939f#p22482
)

**Comment by Djmaximus** [comment]
Hello kovalroma!
To move your Onlyoffice from one server to another you need
1. Copy /app folder from server A to /app folder on server B - in case if there are the same versions of MySQL DB (server A uses MySQL 5.5 - server B should have the same MySQL 5.5)
or
2. You should make dumpfile of MySQL and restore dump in MySQL container. Also you will need to copy _/var/www/onlyoffice/Data_ (this folder is in the Community Server's container) into  _/app/onlyoffice/CommunityServer/data_ (this folder appear after installing Onlyoffice Enterprise Edition on your server)

When you copied **app/onlyoffice** folder to server B you shouldn't start `bash opensource-install.sh -u true`
you should **install** Onlyoffice Community Edition but not to **update** (-u true parameter) - just execute `bash opensource-install.sh`. Also there is a mistake when you tried to installed the Document Server manually with ` -es true` parameter. This parameter installs the Document Server as **E**xternal **S**erver .
So you should
1. Copy _/app/onlyoffice_ folder from server A to server B
2. And install Onlyoffice Community Edition without `-u true` parameter
`bash opensource-install.sh`
It is supposed that there is no Onlyoffice containers installed before on server B.
