### ISSUE TITLE
Mysql Server Connection is sleeping

### ISSUE THREAD

**Issue by benhartwich** [ONLYOFFICE/Docker-CommunityServer#54]
Hi,

I´ve installed onlyoffice communityserver on debian 9 and created an own mariadb database on the same server (running at localhost). The docker log of the community server is showing the following:
```
+ log_debug 'Mysql check connection for 127.0.0.1'
+ echo 'onlyoffice: [Debug] Mysql check connection for 127.0.0.1'
onlyoffice: [Debug] Mysql check connection for 127.0.0.1
+ mysqladmin ping -h 127.0.0.1 -P 3306 -u onlyoffice --password=xyz --silent
+ sleep 1
```
I don´t know, what I´m doing wrong? I´ve created an empty database and the user onlyoffice has all rights on this database.

This is my startup command:
```
docker run --net onlyoffice -i -t -d --restart=always --name onlyoffice-community-server -p 127.0.0.1:8090:80 \
 -e MYSQL_SERVER_HOST=127.0.0.1 \
 -e MYSQL_SERVER_PORT="3306"\
 -e MYSQL_SERVER_DB_NAME=onlyoffice \
 -e MYSQL_SERVER_USER=onlyoffice \
 -e MYSQL_SERVER_PASS=xyz \
 -e DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server \
 -v /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data \
 -v /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice \
 onlyoffice/communityserver
```
I´ve created the docker network bridge and the document server runs. Has anyone a hint, why the mysql connection is sleeping?

**Comment by Carazyda** [comment]
Hello @benhartwich  sorry for a late answer. Why you don't want run mysql in the same docker container? Connection from container to host machine is [difficult](https://forums.docker.com/t/accessing-host-machine-from-within-docker-container/14248). We recommend to you run all in docker containers.

**Comment by benhartwich** [comment]
Hi,
thanks for your answer. But how can I ensure, that the mysql database is backup on a docker pull / update of your software?

**Comment by Carazyda** [comment]
If you mapped folders to host (-v parameter) - all data stored on host machine. On update you create a new containers with the same -v parameters.

**Comment by benhartwich** [comment]
Can you show me an example please, which should be working? My database is on the same machine, but outside of the docker container. 
I´ve tried the startup command posted above without any mysql settings, but it doesnt work either.

**Comment by Carazyda** [comment]
We describe in [this](https://github.com/ONLYOFFICE/Docker-CommunityServer#installing-mysql) section. If you want to move data from host mysql to docker mysql - just copy corresponding folders.

If you run docker containers for the first time and by default - we recommend use our script opensource-install.sh

**Comment by benhartwich** [comment]
Thanks, got it running without the mysql settings! Error was on my site!
