### ISSUE TITLE
CommunityServer does not start if DocumentServer started earlier

### ISSUE THREAD

**Issue by HenriWahl** [ONLYOFFICE/Docker-CommunityServer#56]
Hi,
great product anyway, but I run into a problem when the DocumentServer container is started before CommunityServer. The latter then claims a PID is already used:

> [ OK ]
,+ '[' ']'
,+ '[' ']'
,+ '[' onlyoffice-document-server ']'
,+ DOCUMENT_SERVER_ENABLED=true
,+ DOCUMENT_SERVER_HOST=onlyoffice-document-server
,+ DOCUMENT_SERVER_HOST_PROXY='localhost\/ds-vpath'
,+ DOCUMENT_SERVER_API_URL='\/ds-vpath'
,+ '[' true == true ']'
,+ '[' 10.200.0.2/16 ']'
,+ '[' -z '' ']'
,++ dig +short onlyoffice-document-server
,+ DOCUMENT_SERVER_HOST_IP=10.17.18.4
,+ check_ip_is_internal 10.200.0.2/16 10.17.18.4
,+ local 'IPRE=\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)'
,+ IP=($(echo "$1" | sed -ne 's:^'"$IPRE"'/.*$:\1 \2 \3 \4:p'))
,++ echo 10.200.0.2/16
,++ sed -ne 's:^\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)/.*$:\1 \2 \3 \4:p'
,+ local IP
,+ MASK=($(echo "$1" | sed -ne 's:^[^/]*/'"$IPRE"'$:\1 \2 \3 \4:p'))
,++ echo 10.200.0.2/16
,++ sed -ne 's:^[^/]*/\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)$:\1 \2 \3 \4:p'
,+ local MASK
,+ '[' 0 -ne 4 ']'
,+ BITCNT=($(echo "$1" | sed -ne 's:^[^/]*/\([0-9]\+\)$:\1:p'))
,++ echo 10.200.0.2/16
,++ sed -ne 's:^[^/]*/\([0-9]\+\)$:\1:p'
,+ local BITCNT
,+ BITCNT=4294901760
,+ (( I=0 ))
,+ (( I<4 ))
,+ MASK[$I]=255
,+ (( I++  ))
,+ (( I<4 ))
,+ MASK[$I]=255
,+ (( I++  ))
,+ (( I<4 ))
,+ MASK[$I]=0
,+ (( I++  ))
,+ (( I<4 ))
,+ MASK[$I]=0
,+ (( I++  ))
,+ (( I<4 ))
,+ NETWORK=()
,+ local NETWORK
,+ (( I=0 ))
,+ (( I<4 ))
,+ NETWORK[$I]=10
,+ (( I++  ))
,+ (( I<4 ))
,+ NETWORK[$I]=200
,+ (( I++  ))
,+ (( I<4 ))
,+ NETWORK[$I]=0
,+ (( I++  ))
,+ (( I<4 ))
,+ NETWORK[$I]=0
,+ (( I++  ))
,+ (( I<4 ))
,+ INIP=($(echo "$2" | sed -ne 's:^'"$IPRE"'$:\1 \2 \3 \4:p'))
,++ echo 10.17.18.4
,++ sed -ne 's:^\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)$:\1 \2 \3 \4:p'
,+ local INIP
,+ (( I=0 ))
,+ (( I<4 ))
,+ [[ 10 -ne 10 ]]
,+ (( I++  ))
,+ (( I<4 ))
,+ [[ 17 -ne 200 ]]
,+ exit 0
,+ SERVER_HOST=
,+ ONLYOFFICE_DIR=/var/www/onlyoffice
,+ ONLYOFFICE_DATA_DIR=/var/www/onlyoffice/Data
,+ ONLYOFFICE_PRIVATE_DATA_DIR=/var/www/onlyoffice/Data/.private
,+ ONLYOFFICE_SERVICES_DIR=/var/www/onlyoffice/Services
,+ ONLYOFFICE_SQL_DIR=/var/www/onlyoffice/Sql
,+ ONLYOFFICE_ROOT_DIR=/var/www/onlyoffice/WebStudio
,+ ONLYOFFICE_APISYSTEM_DIR=/var/www/onlyoffice/ApiSystem
,+ ONLYOFFICE_MONOSERVER_PATH=/etc/init.d/monoserve
,+ ONLYOFFICE_HYPERFASTCGI_PATH=/etc/hyperfastcgi/onlyoffice
,+ ONLYOFFICE_MONOSERVE_COUNT=1
,+ ONLYOFFICE_MODE=SERVER
,+ ONLYOFFICE_GOD_DIR=/etc/god/conf.d
,+ ONLYOFFICE_CRON_DIR=/etc/cron.d
,+ ONLYOFFICE_CRON_PATH=/etc/cron.d/onlyoffice
,++ ip -o -f inet addr show
,++ awk '/scope global/ {print $4}'
,++ head -1
,+ DOCKER_ONLYOFFICE_SUBNET=10.200.0.2/16
,++ ip addr show eth0
,++ awk '/inet / {gsub(/\/.*/,"",$2); print $2}'
,++ head -1
,+ DOCKER_CONTAINER_IP=10.200.0.2
,+ DOCKER_CONTAINER_NAME=onlyoffice-community-server
,+ DOCKER_ENABLED=true
,+++ dirname /app/onlyoffice/run-community-server.sh
,++ cd /app/onlyoffice
,++ pwd
,+ DIR=/app/onlyoffice
,+ NGINX_CONF_DIR=/etc/nginx/sites-enabled
,++ grep processor /proc/cpuinfo
,++ wc -l
,+ NGINX_WORKER_PROCESSES=4
,++ ulimit -n
,+ NGINX_WORKER_CONNECTIONS=65536
,+ SERVICE_SSO_AUTH_HOST_ADDR=
,++ sudo sed -n '/"core.machinekey"/s!.*value\s*=\s*"\([^"]*\)".*!\1!p' /var/www/onlyoffice/WebStudio/web.appsettings.config
,+ DEFAULT_ONLYOFFICE_CORE_MACHINEKEY='Vskoproizvolny Salt par Chivreski'
,+ ONLYOFFICE_CORE_MACHINEKEY='Vskoproizvolny Salt par Chivreski'
,+ '[' '!' -d /var/www/onlyoffice/Data/.private ']'
,+ echo 'Vskoproizvolny Salt par Chivreski'
,+ chmod -R 444 /var/www/onlyoffice/Data/.private
,+ cat /proc/1/cgroup
,+ grep -qE 'docker|lxc'
,+ DOCKER_ENABLED=true
,+ '[' '!' -d /etc/nginx/sites-enabled ']'
,+ '[' '!' -d /var/www/onlyoffice/DocumentServerData ']'
,+ NGINX_ROOT_DIR=/etc/nginx
,+ VALID_IP_ADDRESS_REGEX='^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$'
,+ LOG_DEBUG=DEBUG
,+ LOG_DIR=/var/log/onlyoffice/
,+ ONLYOFFICE_HTTPS=false
,+ SSL_CERTIFICATES_DIR=/var/www/onlyoffice/Data/certs
,+ SSL_CERTIFICATE_PATH=/var/www/onlyoffice/Data/certs/onlyoffice.crt
,+ SSL_KEY_PATH=/var/www/onlyoffice/Data/certs/onlyoffice.key
,+ SSL_CERTIFICATE_PATH_PFX=/var/www/onlyoffice/Data/certs/onlyoffice.pfx
,+ SSL_CERTIFICATE_PATH_PFX_PWD=onlyoffice
,+ SSL_DHPARAM_PATH=/var/www/onlyoffice/Data/certs/dhparam.pem
,+ SSL_VERIFY_CLIENT=off
,+ SSL_OCSP_CERTIFICATE_PATH=/var/www/onlyoffice/Data/certs/stapling.trusted.crt
,+ CA_CERTIFICATES_PATH=/var/www/onlyoffice/Data/certs/ca.crt
,+ ONLYOFFICE_HTTPS_HSTS_ENABLED=true
,+ ONLYOFFICE_HTTPS_HSTS_MAXAGE=63072000
,+ SYSCONF_TEMPLATES_DIR=/app/onlyoffice/config
,+ mkdir -p /app/onlyoffice/config/nginx
,+ SYSCONF_TOOLS_DIR=/app/onlyoffice/assets/tools
,+ ONLYOFFICE_SERVICES_INTERNAL_HOST=
,+ ONLYOFFICE_SERVICES_EXTERNAL=false
,+ DOCUMENT_SERVER_ENABLED=false
,+ DOCUMENT_SERVER_JWT_ENABLED=false
,+ DOCUMENT_SERVER_JWT_SECRET=
,+ DOCUMENT_SERVER_JWT_HEADER=
,+ DOCUMENT_SERVER_HOST=
,+ DOCUMENT_SERVER_HOST_PROXY=
,+ DOCUMENT_SERVER_PROTOCOL=http
,+ DOCUMENT_SERVER_API_URL=
,+ DOCUMENT_SERVER_HOST_IP=
,+ CONTROL_PANEL_ENABLED=false
,+ MAIL_SERVER_ENABLED=false
,+ MYSQL_SERVER_ROOT_PASSWORD=
,+ MYSQL_SERVER_HOST=localhost
,+ MYSQL_SERVER_PORT=3306
,+ MYSQL_SERVER_DB_NAME=onlyoffice
,+ MYSQL_SERVER_USER=root
,+ MYSQL_SERVER_PASS=
,+ MYSQL_SERVER_EXTERNAL=false
,+ mkdir -p /var/www/onlyoffice/Data/certs/.well-known/acme-challenge
,+ check_partnerdata
,+ PARTNER_DATA_FILE=/var/www/onlyoffice/Data/json-data.txt
,+ '[' -f /var/www/onlyoffice/Data/json-data.txt ']'
,+ re='^[0-9]+$'
,+ [[ 1 =~ ^[0-9]+$ ]]
,+ cp /etc/nginx/includes/onlyoffice-communityserver-nginx.conf.template /etc/nginx/nginx.conf
,+ sed 's/^worker_processes.*/worker_processes 4;/' -i /etc/nginx/nginx.conf
,+ sed 's/worker_connections.*/worker_connections 65536;/' -i /etc/nginx/nginx.conf
,+ cp /etc/nginx/includes/onlyoffice-communityserver-common-init.conf.template /etc/nginx/sites-enabled/onlyoffice
,+ rm -f '/etc/nginx/conf.d/*.conf'
,+ rsyslogd
,Pidfile (and pid) already exist.
,

The last message `Pidfile (and pid) already exist.` seems to be the problem.

I do not use Docker Compose which allows to define dependencies - shouldn't the container be able to start anyway?

**Comment by Carazyda** [comment]
Hello @HenriWahl  What an error you got at web? How do you run containers?

For novice at docker we recommend use our script opensource-install.sh.

**Comment by HenriWahl** [comment]
The error is no response at port 443 - according to the above log because the nginx did not start?

**Comment by HenriWahl** [comment]
I found the error message `Pidfile (and pid) already exist.` comes from rsyslogd.

**Comment by Carazyda** [comment]
Yes, seems like nginx is not started. How do you run containers? Can you specified a commands?

And please try our script opensource-install.sh.

**Comment by HenriWahl** [comment]
As the system is already running in production (or did) I do not want to do a new install - I just would like to get the containers running again.
I configure them via Saltstack. Their docker-run-calls are these, according to runlike:

CommunityServer:

docker run --name=onlyoffice-community-server --hostname=8f8ad2855b16 --env="DOCUMENT_SERVER_PORT_80_TCP_ADDR=onlyoffice-document-server" --env="EXTERNAL_IP=172.19.17.18" --env="http_proxy=http://172.19.13.12:3128" --env="https_proxy=http://172.19.13.12:3128" --env="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" --env="LANG=en_US.UTF-8" --env="LANGUAGE=en_US:en" --env="LC_ALL=en_US.UTF-8" --volume="/data/onlyoffice/CommunityServer/logs:/var/log/onlyoffice" --volume="/data/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data" --volume="/data/onlyoffice/DocumentServer/data:/var/www/onlyoffice/DocumentServerData" --volume="/data/mysql:/var/lib/mysql" --volume="/var/log/onlyoffice" --volume="/var/www/onlyoffice/Data" --volume="/var/lib/mysql" --volume="/var/www/onlyoffice/DocumentServerData" --expose=9888 --expose=9866 --expose=3306 --expose=5222 --expose=5280 --expose=9882 --expose=9871 -p 80:80 --expose=9865 -p 443:443 --restart=always --label maintainer="Ascensio System SIA <support@onlyoffice.com>" --label onlyoffice.community.release-date="20180912" --label onlyoffice.community.version="9.6.3.691" --label onlyoffice.community.release-date.sign="ASC 20180912:20180912103421:r+cj0OCSYPQIx2H4bXtOEqejjhU=" --detach=true -t onlyoffice/communityserver:latest /app/onlyoffice/run-community-server.sh

DocumentServer:

docker run --name=onlyoffice-document-server --hostname=375a89ed4e32 --env="http_proxy=http://172.19.13.12:3128" --env="POSTGRESQL_SERVER_USER=onlyoffice" --env="POSTGRESQL_SERVER_DB_NAME=onlyoffice" --env="https_proxy=http://172.19.13.12:3128" --env="POSTGRESQL_SERVER_PASS=onlyoffice" --env="POSTGRESQL_SERVER_HOST=onlyoffice-postgresql" --env="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" --env="LANG=en_US.UTF-8" --env="LANGUAGE=en_US:en" --env="LC_ALL=en_US.UTF-8" --env="DEBIAN_FRONTEND=noninteractive" --volume="/data/onlyoffice/DocumentServer/logs:/var/log/onlyoffice" --volume="/data/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data" --volume="/data/onlyoffice/lib:/var/lib/onlyoffice" --volume="/var/log/onlyoffice" --volume="/usr/share/fonts/truetype/custom" --volume="/var/lib/onlyoffice" --volume="/etc/onlyoffice" --volume="/var/lib/postgresql" --volume="/var/www/onlyoffice/Data" --expose=443 --expose=80 --restart=always --label maintainer="Ascensio System SIA <support@onlyoffice.com>" --detach=true -t onlyoffice/documentserver:latest

**Comment by Carazyda** [comment]
Where you get all this parametres? We dont described this in our instructions. 

I cant reproduce this error, think problem in your proxy or network. Can you try run container without your environment (just one "-p" parameter)?

**Comment by HenriWahl** [comment]
As I set up OnlyOffice via Saltstack I do not know the exact docker run call, but I found runlike to get exactly this information:

`docker run -v /var/run/docker.sock:/var/run/docker.sock --rm assaflavie/runlike onlyoffice-document-server`

**Comment by Carazyda** [comment]
It doesn't seem like the right run command
> docker run -v /var/run/docker.sock:/var/run/docker.sock --rm assaflavie/runlike onlyoffice-document-server

Please run containers as we described in instructions, or use our script opensource-install.sh.

**Comment by HenriWahl** [comment]
This is the run command to find out what parameters our Saltstack runs onlyoffice-document-server with.

**Comment by HenriWahl** [comment]
OK. I will try with the latest instructions and see what happens.
