### ISSUE TITLE
 Docker-DocumentServer Connection with Docker-Community Server Api url: Service is not defined

### ISSUE THREAD

**Issue by petrukngantuk** [ONLYOFFICE/Docker-CommunityServer#67]
Can any one help me fixing this issue?
I'm using docker version using this https://helpcenter.onlyoffice.com/server/docker/community/install-integrated.aspx,

It's successfull,

then I restore my backup data and mysqldump (onlyoffice and onlyoffice_mailserver),

then I can't access is, mybe it's related to this : docs
https://helpcenter.onlyoffice.com/server/linux/community/connect-document-server.aspx
https://helpcenter.onlyoffice.com/server/windows/community/connect-document-server.aspx

But I'm not sure, not finding the correct 'ID' in 'webstudio_settings' table in onlyoffice database

**Comment by petrukngantuk** [comment]
is there a way to reset the connection?

**Comment by petrukngantuk** [comment]
root@3ae0691427a9:/# curl -Ik http://onlyoffice-community-server/web-apps/apps/api/documents/api.js
HTTP/1.1 404 Not Found
Server: nginx
Date: Thu, 29 Aug 2019 14:09:03 GMT
Content-Type: text/html
Content-Length: 118218
Connection: keep-alive
Last-Modified: Thu, 18 Oct 2018 09:45:58 GMT
X-AspNet-Version: 4.0.30319
Cache-Control: private
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload

**Comment by alexanderonlyoffice** [comment]
Hello @petrukngantuk, please specify if you installed all components (Community Server, Document Server and Mail Server) on the one server or on separate servers. 

1. Please send the output of `sudo docker ps` command.
2. Send me also the screenshot of Document Service address settings (Settings module -> Integration -> Document Service).
3. Send me a screenshot of the error you get in web interface.
4. How did you restore the backup?
