### ISSUE TITLE
Upload and export/download not working

### ISSUE THREAD

**Issue by C-Duv** [ONLYOFFICE/Docker-CommunityServer#7]
I cannot upload document from my computer to ONLYOFFICE: I do get to select the file I want to upload (browser's job) and the background upload popup (in lower right corner). But upload seems to never start nor finish: progress bar stays at 0%.

I also cannot export a document from ONLYOFFICE (either to Office format, CSV, HTML, etc.).
I do get to choose my export format but nothing happens: no browser download prompt.

As a workaround: is there a way to retrieve files from data dir on the server?

I run container with:

```
docker run -i -t -d \
     --name onlyoffice-document-server \
     onlyoffice/documentserver
 docker run -i -t -d \
     --name onlyoffice-community-server \
     --restart=always \
     -p 8080:80 \
     --link onlyoffice-document-server:document_server \
     -v /opt/onlyoffice/logs:/var/log/onlyoffice \
     -v /opt/onlyoffice/data:/var/www/onlyoffice/Data \
     -v /opt/onlyoffice/mysql:/var/lib/mysql \
     onlyoffice/communityserver
```

**Comment by ibnpetr** [comment]
Hello 
The issue may be in the access access rights to the /var/www/onlyoffice/Data or /opt/onlyoffice/data
The files can always be found in the  /opt/onlyoffice/data (path for the host machine)
Anyway we do recommend using http://download.onlyoffice.com/install/opensource-install.sh for installing an OpenSource version
Best regards
