### ISSUE TITLE
wrong cpu processor count!

### ISSUE THREAD

**Issue by tufand** [ONLYOFFICE/Docker-CommunityServer#71]
hi,

i'm discovered on /app/onlyoffice/run-community-server.sh CPU_PROCESSOR_COUNT wrong value returned.

my manually set file and mount bind container. solved my elasticsearch service allways failback problems.
![onlyoffice-community-server-docker-not-onemli](https://user-images.githubusercontent.com/31701244/65524978-6b4ce280-def7-11e9-99a2-e1ff368c4822.PNG)

**Comment by Carazyda** [comment]
Hello @tufand on our test machines script and `grep processor /proc/cpuinfo | wc -l` work well. What OS are you using? And what conclusion do you get after the command?

**Comment by tufand** [comment]
Hello @Carazyda running system detail contain is picture
![1](https://user-images.githubusercontent.com/31701244/65598526-51b5a480-dfa4-11e9-8318-572c7dee3a31.PNG)

this container use 2 CPU

**Comment by tufand** [comment]
CPU_PROCESSOR_COUNT  if possible the configuration parameter ENV  value add as feature new release ?

![1](https://user-images.githubusercontent.com/31701244/65599025-7a8a6980-dfa5-11e9-8f29-3542402e0a98.PNG)

**Comment by tufand** [comment]
define environment value CPU_PROCESSOR_COUNT  work proply.
