### ISSUE TITLE
Onlyoffice stops responding / disk full / possibly no inodes available

### ISSUE THREAD

**Issue by mmccarn** [ONLYOFFICE/Docker-CommunityServer#79]
I'm using onlyoffice integrated with Nextcloud.

Onlyoffice stopped responding a couple weeks ago.

Ultimately, I discovered that I had over 1.25 million elasticsearch *directories* in /var/lib/overlay2/.../diff/tmp (plus, probably, another 1.25M+ fifo pipes)

I did not check at the time, but I now suspect that I was out of inodes on my server, since I was getting disk full errors but 'df -h' did not show any devices that were out of space.  ```df -i /``` now reports 2.3M inodes available -- so 1.25M known *directories* with another probable 1.25M pipes would have used up my inodes.
```
# df -i /
Filesystem      Inodes  IUsed   IFree IUse% Mounted on
/dev/sda2      2621440 306929 2314511   12% /
```

After cleaning out the docker .../diff/tmp/... pipes, files, and folders, onlyoffice is working normally again.

For reference, here is what I did to clean out .../diff/tmp/... (and where I got the 1.25M count of directories):
```
sudo -i
docker stop onlyoffice-community-server
docker stop onlyoffice-document-server
docker stop onlyoffice-mysql-server
cd /var/lib/docker/overlay2
COUNT=0
find . -path "*/diff/tmp/*" -type d |while read dir; do COUNT=$((COUNT+1)); if [ $(($COUNT % 1000)) -eq 0 ]; then printf "\r%'.0f" "$COUNT"; fi;  'rm' -rf "$dir"; done
```

Server details:
  * ubuntu 18.0.4.2 installed May 2019
  * Onlyoffice Community Server installed using (opensource-install.sh)[http://download.onlyoffice.com/install/opensource-install.sh]
  * I use this command regularly to check for updates:
      ```echo "Y" |sudo bash /home/mmccarn/addons/opensource-install.sh -u true -dv latest -cv latest -ids true -icp false -ims false```

**Comment by Carazyda** [comment]
Hello @mmccarn why you installed Onlyoffice community server, if you use Nextcloud? How often do you use community server and how much data uploaded-created on this? And how many GB have your disk?

**Comment by mmccarn** [comment]
I don't use the community server.  I take it from your question that I can disable it; I didn't know any better when I setup the server.

Should I uninstall it and close this issue, or leave it installed to work on why my installation is sprouting tmp files?

**Comment by Carazyda** [comment]
Can you describe me how you installed onlyoffice and nextcloud? How you run `opensource-install.sh`? And `docker ps` for now?

**Comment by mmccarn** [comment]
Summary:
  * Nextcloud
    * Proxmox (qemu) guest
      * 500Gb Disk
      * 3Gb RAM
      * 2 x CPU
    * Ubuntu 18.04.3 LTS
    * PHP-FPM 7.3
    * v18.0.0.1 (continuously updated from v10.0.1)
    * [mmccarn-nextcloud-config-2020-01-24.md.zip](https://github.com/ONLYOFFICE/Docker-CommunityServer/files/4108314/mmccarn-nextcloud-config-2020-01-24.md.zip)
  * OnlyOffice
    * Proxmox (qemu) guest
      * 40 Gb Disk
      * 4 Gb RAM
      * 4 x CPU
    * Separate server on LAN
    * Ubuntu 18.04.3 LTS
    * Installed using [opensource-install.sh](http://download.onlyoffice.com/install/opensource-install.sh)
      ```echo "Y" |sudo bash /home/mmccarn/addons/opensource-install.sh -u true -dv latest -cv latest -ics true -ids true -icp false -ims false```
    * self-signed cert with [HSTS disabled](https://cloud.onlyoffice.org/viewtopic.php?t=16114)

Onlyoffice App config from Nextcloud server:
```
# occ config:list onlyoffice
{
    "apps": {
        "onlyoffice": {
            "DocumentServerInternalUrl": "https:\/\/docker.mmsionline.us\/ds-vpath\/",
            "DocumentServerUrl": "https:\/\/docker.mmsionline.us\/ds-vpath\/",
            "StorageUrl": "https:\/\/cloud.mmsionline.us\/",
            "customizationChat": "true",
            "customizationCompactHeader": "true",
            "customizationFeedback": "true",
            "customizationHelp": "true",
            "customizationReadOnly": "true",
            "customizationToolbarNoTabs": "true",
            "defFormats": "{\"csv\":\"false\",\"doc\":\"true\",\"docm\":\"false\",\"docx\":\"true\",\"dotx\":\"false\",\"epub\":\"false\",\"html\":\"false\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"true\",\"pdf\":\"false\",\"potm\":\"false\",\"potx\":\"false\",\"ppsm\":\"false\",\"ppsx\":\"false\",\"ppt\":\"false\",\"pptm\":\"false\",\"pptx\":\"true\",\"rtf\":\"false\",\"txt\":\"false\",\"xls\":\"true\",\"xlsm\":\"false\",\"xlsx\":\"true\",\"xltm\":\"false\",\"xltx\":\"false\"}",
            "demo": "{\"available\":true,\"enabled\":false,\"start\":{\"date\":\"2020-01-18 15:53:03.426450\",\"timezone_type\":3,\"timezone\":\"UTC\"}}",
            "editFormats": "{\"csv\":\"false\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"true\",\"rtf\":\"false\",\"txt\":\"false\"}",
            "enabled": "yes",
            "groups": "[]",
            "installed_version": "4.1.1",
            "jwt_secret": "",
            "sameTab": "true",
            "settings_error": "Bad healthcheck status",
            "types": "filesystem"
        }
    }
}
```

```
# docker ps --no-trunc
CONTAINER ID                                                       IMAGE                               COMMAND                                                           CREATED             STATUS              PORTS                                                                                                                               NAMES
e4d7adf5f0776c088a5d6267694cc89e13da8347557490379c5cb5ee8ca468bf   onlyoffice/communityserver:latest   "/usr/bin/dumb-init -- /app/onlyoffice/run-community-server.sh"   11 hours ago        Up 11 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 3306/tcp, 5280/tcp, 9865-9866/tcp, 9871/tcp, 9882/tcp, 0.0.0.0:5222->5222/tcp, 9888/tcp   onlyoffice-community-server
ca50873327be5f16d7436f0b925a8e074ac59e330e0680cdad6c4112df99cb6b   onlyoffice/documentserver:latest    "/bin/sh -c /app/onlyoffice/run-document-server.sh"               7 months ago        Up 11 hours         80/tcp, 443/tcp                                                                                                                     onlyoffice-document-server
ff62a62d65579fea65f9dfac2a7e6ae618af437c3bca6dae083e778f546b615a   mysql:5.7.26                        "docker-entrypoint.sh mysqld"                                     8 months ago        Up 11 hours         3306/tcp, 33060/tcp
```

Also - I ran these commands on my server last night to see if I could use nextcloud/document server without having the community server installed (it didn't work for me, so I'm back to my original config).  I have just over 6000 new elasticsearch tmp files created since reinstalling onlyoffice-community-server 11 hours ago...
```
# docker ps shows onlyoffice-community-server has container ID e20ae636d839
docker stop e20ae636d839
docker rm e20ae636d839
reboot
# 
# try various things in nextcloud and onlyoffice to get them connected unsuccessfully
# reinstall onlyoffice 
sudo docker volume ls -qf dangling=true |grep . && sudo docker volume rm $(sudo docker volume ls -qf dangling=true)
echo "Y" |sudo docker system prune --all --volumes
sudo find /var/lib/docker/overlay2 -path "*/diff/tmp/*" -type f ! -mtime -10 -delete
echo "Y" |sudo bash /home/mmccarn/addons/opensource-install.sh -u true -dv latest -cv latest -ics true -ids true -icp false -ims false
```

Finally - I keep pretty detailed notes on software installs and server updates if you need more than this.

**Comment by Carazyda** [comment]
The easiest way to resolve your problem - uninstall Onlyoffice Community Edition, delete all containers and /app/onlyoffice/ directory, and run Onlyoffice Document Server `bash opensource-install.sh -ics false -ims false -es true`.

Also you can install Onlyoffice Document Server and Nextcloud on the same server. For this, please look at this [repo](https://github.com/ONLYOFFICE/onlyoffice-nextcloud), or If you want use docker - in this [repo](https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud).

What about elasticsearch tmp files - we will have additional tests to reproduce this problem.

**Comment by mmccarn** [comment]
Thanks.

I'll work on reconfiguring my Nextcloud/Onlyoffice configuration.

I'll keep the existing VM image in case it would be useful for testing anything in the future.
