### ISSUE TITLE
"/discbundle/common" assets are not served

### ISSUE THREAD

**Issue by C-Duv** [ONLYOFFICE/Docker-CommunityServer#8]
The _/discbundle/common/css/..._ and _/discbundle/common/javascript/..._ URLs are not served: I get a 404 which breaks the UI.

Others URLs are OK:
- /wizard.aspx
- /skins/default/images/...
- /clientscript/...

Nginx logs in _/var/log/onlyoffice_ stays empty.

Steps to reproduce:

``` Shell
mkdir /opt/onlyoffice/logs/{data,logs,mysql}
docker run -i -t -d \
    --name onlyoffice-document-server \
    onlyoffice/documentserver
docker run -i -t -d \
    --name onlyoffice-community-server \
    --restart=always \
    -p 127.0.0.1:6000:80 \
    --link onlyoffice-document-server:document_server \
    -v /opt/onlyoffice/logs:/var/log/onlyoffice \
    -v /opt/onlyoffice/data:/var/www/onlyoffice/Data \
    -v /opt/onlyoffice/mysql:/var/lib/mysql \
    onlyoffice/communityserver
```

Version:
- Debian 8.4
- Kernel 3.16.0-4-amd64
- Docker 1.11.0, build 4dc5990

**Comment by Dean13** [comment]
Sorry for the delay. 

In case the issue is still actual, please try following: 

- Delete folder /var/www/onlyoffice/Data/bundle
- Empty cache of redis-server:

```
sudo redis-cli flushall
sudo service redis-server restart
```

- restart monoserve and monoserve2 services.
