### ISSUE TITLE
Onlyoffice Community edition asks for entreprise licence

### ISSUE THREAD

**Issue by Sagittarius-B** [ONLYOFFICE/Docker-CommunityServer#80]
Hi

I have installed the docker image of onlyoffice communityedition through the opensource-install.sh, which proceeds to download run the install.sh script, which then downloads several images : 

5.4.2.46: Pulling from onlyoffice4enterprise/documentserver-ee
2.8.0.290: Pulling from onlyoffice4enterprise/controlpanel-ee
10.5.1.1028: Pulling from onlyoffice4enterprise/communityserver-ee

When the containers are running and I log in to the web interface, I am prompted by a registration panel that asks for a license..
Did I miss something ?

**Comment by Carazyda** [comment]
Hello @Sagittarius-B how do you run our scripts to install onlyoffice? `bash opensource-install.sh -ims false` will install Community Edition, free and no needs license. You are currently installing Enterprise Edition, that need license file.

**Comment by Sagittarius-B** [comment]
I did run bash `bash opensource-install.sh -ims false` but the script fails to download the install.sh script (i am behind corporate proxy), so I downloaded it manually and ran `bash install.sh -ims false`.

**Comment by Carazyda** [comment]
How could you download opensource-install.sh if they are on the same server? :) anyway, if you want to use install.sh, add the `-os true` parameter.

**Comment by Sagittarius-B** [comment]
I may have misspoken. The proxy settings are fine, that's how I downlaoded the opensource-community.sh by `wget https://download.onlyoffice.com/install/opensource-install.sh`

This script calls curl, which works fine outside of the script, but for some reason the opensource-install.sh could not fetch it.

Anyway, the point is that running `sh install.sh -ims false` apparently didn't download the right images. Running `sh install.sh -ims false -os true` is downloading different ones.

Thanks for the tip, will keep you updated.

**Comment by Carazyda** [comment]
install.sh used for install the docker version of Onlyoffice, and default this install Enterprise Edition. To install Community Edition you need run opensource-install.sh or add -os true option to install.sh. And CE is placed in another docker repo.

**Comment by Sagittarius-B** [comment]
So I ran the script with the option you suggested , `sh install.sh -ims false -os true`
It downloaded the mysql library but stopped when it came the documentserver with this error : 

`Docker pull argument exception: repository=onlyoffice/documentserver, tag=`
Any ideas what might cause this?

**Comment by Carazyda** [comment]
Because your machine can not connect to docker hub with curl command. Please specify versions in script parameters `bash install.sh -ims false -os true -cv 10.5.1.1028 -dv 5.4.2.46`.

**Comment by Sagittarius-B** [comment]
Sorry for the late answer, I finally managed to install the correct images. I now have document-server running in a docker container and I am able to access it wia HTTP.
I would like to link it to nextcloud which require a HTTPS access. In put the 3 files in the data/certs folder as per your documentation and started the container with `docker run -i -t -d -p 443:443 --restart=always \
-v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data  onlyoffice/documentserver` but i can't access the document-server (this site can't be reached error).

I didn't find any configuration files similar to my previous install of document-server (installed via yum).

**Comment by Carazyda** [comment]
For run Nextcloud and Onlyoffice Document Server please look at this [repo](https://github.com/ONLYOFFICE/onlyoffice-nextcloud), or if you want use docker - this [repo](https://github.com/ONLYOFFICE/docker-onlyoffice-nextcloud). You don't need Onlyoffice Community Edition for this.

What about ssl on the document server, please read our instructions carefully at [helpcenter](https://helpcenter.onlyoffice.com/server/docker/document/docker-installation.aspx), and if you have any problems - please open issue in correct repo.
