### ISSUE TITLE
add more information, how to adapt docker-compose

### ISSUE THREAD

**Issue by rubo77** [ONLYOFFICE/Docker-CommunityServer#88]
If you install via docker-compose, you have to adapt some variables in the file. please add more instructions, what you have to change and what can stay the default way.

for example, you have to change the database passwords

I tried this, set passwords in all lines, that offer passwords,  but now I get the repeating error

     Access denied for user 'onlyoffice_mailserver_user'@'onlyoffice-community-server.nextcloud-onlyoffice_onlyoffice
     Access denied for user 'onlyoffice_user'@'onlyoffice-community-server.nextcloud-onlyoffice_onlyoffice'

**Comment by Carazyda** [comment]
Hello @rubo77 yes we have a problem with setup another password for mysql in docker-compose. You can also use our script and setup password by parameters. For more info run script with -h parameter.

**Comment by rubo77** [comment]
So I really  have to leave the mysql root password on literally `my-secret-password`?

Can I change the outer ports for mail, http, https? since I already use those ports in another docker-container

**Comment by Carazyda** [comment]
root password you can change in docker-compose.yml, but not for onlyoffice_user. Ports you can also change in yml file. But we recommend using onlyoffice as single on one server.

**Comment by rubo77** [comment]
I ued the default docker-compose.yaml with default passwords now but again I get this error:

     Access denied for user 'onlyoffice_user'@'onlyoffice-community-server.nextcloud-onlyoffice_onlyoffice' (using password: YES)         

I only changed the ports: https://paste.toppoint.de/?9f4e221ed6395bad#sgxX43vHv2vR+XnSr4XYpsMfzmptssq5TrpUvuZt/WA=

**Comment by rubo77** [comment]
Maybe do I have to checkout a release tag instead of current master?

**Comment by Carazyda** [comment]
Perhaps somewhere the old password in configs was saved. Try a clean install.

**Comment by rubo77** [comment]
i removed and deleted the docker containers, so it was a clean install, wasn't it?

**Comment by Carazyda** [comment]
Please also delete and reload this repo.

**Comment by rubo77** [comment]
I deleted everything and restartd, now I get this error:

```+ MAIL_SERVER_API_PORT=8081                                                                                                                                       
+ MAIL_SERVER_API_HOST=onlyoffice-mail-server                                                                                                                     + MAIL_SERVER_DB_HOST=onlyoffice-mysql-server                                                                                                                     
+ MAIL_SERVER_DB_PORT=3306                                                                                    
+ MAIL_SERVER_DB_NAME=onlyoffice_mailserver                                                                                                                       
+ MAIL_SERVER_DB_USER=onlyoffice_mailserver_user                                                                                                                  
+ MAIL_SERVER_DB_PASS=onlyoffice_mailserver_user_pass                                                                                                             
+ '[' onlyoffice-mysql-server ']'                                                                                                                                 
+ MAIL_SERVER_ENABLED=true                                                                                                                                        
+ '[' -z onlyoffice-mail-server ']'                                                                                                                               
+ [[ ! onlyoffice-mail-server =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]]
++ dig +short onlyoffice-mail-server                                                                                                                              
+ MAIL_SERVER_API_HOST=                                                                                                                                           
+ '[' -z '' ']'                                                                         
+ echo 'MAIL_SERVER_API_HOST not correct'                                                                                       
MAIL_SERVER_API_HOST not correct                                                                                           
+ exit 502                                                                                   
```

These are my `docker-compose.yaml` changes:
```
diff --git a/docker-compose.yml b/docker-compose.yml
index d4df8a3..bbe804a 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -39,8 +39,8 @@ services:
     networks:
      - onlyoffice
     ports:
-     - '80:80'
-     - '443:443'
+     - '3380:80'
+     - '33443:443'
      - '5222:5222'
     stdin_open: true
     tty: true
@@ -59,8 +59,8 @@ services:
     networks:
       - onlyoffice
     expose:
-      - '80'
-      - '443'
+      - '3380'
+      - '33443'
     volumes:
        - document_data:/var/www/onlyoffice/Data
        - document_log:/var/log/onlyoffice
@@ -71,7 +71,7 @@ services:
     image: onlyoffice/mailserver:latest
     depends_on:
      - onlyoffice-mysql-server
-    hostname: ${MAIL_SERVER_HOSTNAME}
+    hostname: 10.77.77.101
     environment:
        - MYSQL_SERVER=onlyoffice-mysql-server
        - MYSQL_SERVER_PORT=3306
@@ -82,11 +82,11 @@ services:
       - onlyoffice
     restart: always
     privileged: true
-    ports: ['25:25','143:143','587:587']
+    ports: ['3325:25','33143:143','33587:587']
     stdin_open: true
     tty: true
     expose:
-      - '8081'
+      - '38081'
     volumes:
       - mail_data:/var/vmail
       - mail_certs:/etc/pki/tls/mailserver
```

I also tried hostname: mail.mydomain.de but the same error

**Comment by rubo77** [comment]
Maybe we should start this without the mailserver, if we find a solution here: #92

**Comment by Carazyda** [comment]
This error means, that community-server cannot resolve ip of mail-server, maybe container not started, need to check it for errors. Or you can install without mail-server, if you dont need it.

**Comment by rubo77** [comment]
strange: after a reboot of the docker-guest VM which restarted  all docker-containers also the ONLYOFFICE docker containers all started fine and the service is up and running now :-?

**Comment by rubo77** [comment]
Now there is the part in the Readme:

>To restrict the access to ONLYOFFICE Document Server and for security reasons and data integrity the encrypted signature is used. Specify the Secret key in the Nextcloud administrative configuration. In the ONLYOFFICE Document Server config file specify the same secret key and enable the validation.

It seems like the config file for Linux is `/etc/onlyoffice/documentserver/local.json` which is hidden in the docker-container.

I guess it must be mapped to the outside of docker via a `volume` command in the `docker-compose.yaml` to use this security?

**Comment by Carazyda** [comment]
Maybe after rebooting the container with the mail server started.

You can set the secret in the container.

**Comment by Carazyda** [comment]
This issue was closed due to no response.
