### ISSUE TITLE
Server stuck at "The portal start up process might take some time"

### ISSUE THREAD

**Issue by onnyyonn** [ONLYOFFICE/Docker-CommunityServer#96]
I have installed communityserver, along with mysql, via docker, and set up nginx reverse proxy for it. When I try to access it for the first time, it is stuck at "The portal start up process might take some time, please wait...". I'd appreciate any suggestion to resolve this issue.

**Comment by Carazyda** [comment]
Hello @onnyyonn  please look at logs folder for the errors, and `docker logs` for community server container.

**Comment by onnyyonn** [comment]
Actually I went ahead and installed document server instead of running the whole community server. Unfortunately I don't have the community server container anymore and I won't be able to provide the logs. Please consider this issue to be resolved.

**Comment by Carazyda** [comment]
As you wish. Please close this issue.

**Comment by basaran** [comment]
hi, I have the same problem and docker logs report:

```
Failed to mount tmpfs at /run: Operation not permitted
Failed to mount tmpfs at /run/lock: Operation not permitted
Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```

**Comment by Carazyda** [comment]
Hello @basaran you need to add `--privileged` flag and mapped `-v /sys/fs/cgroup:/sys/fs/cgroup:ro` to docker run command. Please look at repo instructions.

**Comment by basaran** [comment]
Hi, thank you. After following the instructions on github repo, it booted up fine) Before, I was just reading the instructions from the docker page, perhaps it's not in sync with the github page?

Also, this link is broken on the github repo:

https://github.com/ONLYOFFICE/Docker-CommunityServer/blob/master/docker-compose.yml#L26

Thank you again,

**Comment by Carazyda** [comment]
Thanks for your comments. We will definitely update this.
