### ISSUE TITLE
Installation problem 502 Bad Gateway

### ISSUE THREAD

**Issue by N3tFX** [ONLYOFFICE/Docker-CommunityServer#98]
No matter how hard I've tried, I can't make Docker Community Server to work.

This is the command I used: `sudo docker run -i -t -d -p 8080:80 onlyoffice/communityserver`. When trying to connect to the server this is all I see: **_The portal start up process might take some time, please wait..._**. And in the console of firefox developer tools it shows: **_GET http://127.0.0.1:8080/api/2.0/capabilities.json [HTTP/1.1 502 Bad Gateway 1ms]_**. With no firewalls blocking anything.

I have also tried to use the installation script, which all it did was to install more stuff than I wanted, with the same result. The never ending loading screen with the above message.

I am running debian, with Docker version 19.03.12. I have already succesfully install the Document Server and connected it with nextcloud. I also have successfully updated the Document Server docker, but for some reason I can't make the community server work.

**Comment by Carazyda** [comment]
Hello @N3tFX Please look at the errors in the logs, and check docker logs for container community server.

**Comment by N3tFX** [comment]
These are the two errors it shows:

`rsyslogd: run failed with error -3000 (see rsyslog.h or try http://www.rsyslog.com/e/3000 to learn what that number means)`

```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
+ queryResult=
+ echo

+ mysql_check_connection
+ '[' ']'
+ mysqladmin ping -h localhost -P 3306 -u root --password= --silent
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
+ sleep 1
+ mysqladmin ping -h localhost -P 3306 -u root --password= --silent
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
+ sleep 1
```

and it repeats again and again the last ping to mysqladmin.

**Comment by Carazyda** [comment]
You run only community server container? Do you have ipv6 enabled? Please check that mysql is running in container, and try to change in /var/www/onlyoffice/WebStudio/web.connections.config localhost to 127.0.0.1. Or run mysql container separated.

**Comment by N3tFX** [comment]
No ipv6. I've also stopped all other docker containers to avoid any conflict. I tried your suggestions but nothing worked. Same result. But occasionally instead of the **Please wait...** screen it gave me another screen saying: **Application Exception Runtime Error**. Also mysql sometimes didn't run on its own and I had to start it manually. I've also delete any previous container and started from scratch in case any left overs were causing the problem. But no matter what, I always end up in the never ending loading screen with the message on the first post. I think I will leave it for now and try again on a newer version.

**Comment by Carazyda** [comment]
Yes, we have a problem with mysql if run only the community server container. We will fix this in next releases. Now you can run the community server with the mysql server in a separate container.

**Comment by N3tFX** [comment]
I did try using a separate MySQL container, I've even tried MariaDB. Nothing worked. I saw inside the databases that the Community Server docker container created the tables needed, so I know that the communication of the Community Server with the external MySQL database was working. It just wouldn't move from the: **_The portal start up process might take some time, please wait..._** screen. Anyway, for now I will wait for the new docker version.

**Comment by Carazyda** [comment]
Can you provide the errors from web.log, when you run with separate mysql container?

**Comment by N3tFX** [comment]
Sorry, no. I have deleted everything from the docker containers that didn't work and only kept the 9.6.5.771 version that is working.

**Comment by N3tFX** [comment]
I was hopping that with the newer version things would work, but no joy. I just tried the version **_11.0.0.1458_** docker and it's not even starting the services. It complains that the system is not a **_systemd_** system.

**Comment by N3tFX** [comment]
I am closing this issue not because a solution was found, but because a newer version has been released which, to my understanding, works a bit different. I see no reason looking for a solution for an obsolete version.
