### ISSUE TITLE
Timeout while trying to browse through Webdav-Share

### ISSUE THREAD

**Issue by ttjaden** [ONLYOFFICE/Docker-CommunityServer#99]
We have a working setup with Onlyoffice Community and Document Server. A few days ago the functionality of browser through webdav shares and editing files stopped working.

Setup:

> VM1:
> 8 CPU, 16 GB RAM, 100 GB SSD
> Ubuntu Server 20.04 LTS
> Community and Document Server installed with opensource-install.sh without mail-server
> Public Domain with office.domain.com
> 
> VM2:
> 4 CPU, 16 GB RAM, 500 GB SSD
> Ubuntu Server 18.04 LTS
> Nextcloud 19.0.3
> Public Domain with domain.com

I mounted a Nextcloud Webdav-Share and shared it with a group in community server. All worked fine for 5 weeks. Two days ago browsing through the folder structure in community server was slower and opening a docx or xlsx was  often really slow or ended up with an error, that the file was not able to be opened.

Then I updated the VM1 with `bash opensource-install.sh -u true` which updated the document server. Nothing was better. After that i removed the webdav sahre an added it again. Now, when trying to browse through the share it takes some 30seconds ("Loading ... please wait") or so ...
![grafik](https://user-images.githubusercontent.com/16917049/93384973-d2c91400-f865-11ea-8ed0-1b322d735998.png)
... and then it redirects to "My Documents".

Hint:
The Nextcloud side has no problems. No error logs there. Browser directly through the webdav share ist no problem an editing files from within the nextcloud interface with Onlyoffice is also no problem.

Does anybody has a solution for our problem?

**Comment by ttjaden** [comment]
Edit:
I tried two different webdav-services (magentacloud an another Nextcloud in version 18). Those two services work. The webdav share that doesn't work is from a Nextcloud 19.0.3.

I had a look on the last Update (19.0.2 -> 19.0.3): In the release news there is one point regarding "dav", see https://github.com/nextcloud/viewer/pull/582

--> Could this update be the problem for Onlyoffice Community Server to load the webdav directiory?

**Comment by Carazyda** [comment]
Hello @ttjaden Please check the web.files.log, web.api.log and web.log for the errors. Maybe some happens in your network or servers network?

**Comment by ttjaden** [comment]
@Carazyda : I tried to integrate the webdav share and afterwards i downloaded all the logs you've said.

within `web.files.log` I found
```
  at ASC.Web.Files.Services.DocumentService.DocumentServiceConnector.GetConvertedUri (System.String documentUri, System.String fromExtension, System.String toExtension, System.String documentRevisionId, System.String password, System.Boolean isAsync, System.String& convertedDocumentUri) [0x00038] in <c1973b05c8414a40bb633c2cd827ba68>:0 
  at ASC.Web.Files.Utils.FileConverter.CheckConvertFilesStatus (System.Object _) [0x002f2] in <c1973b05c8414a40bb633c2cd827ba68>:0 
```
Within the other log-files I didn't find somethind "strange" but on the other side, I don't know for what I have to look out!?

**Comment by Carazyda** [comment]
@ttjaden Can you show the error text from date? For this fragment of log i can't say something. And also please check console and network of browser for the errors, when you redirect to My Documents folder.

**Comment by ttjaden** [comment]
Unfortunately I don't find the time to look for the errors. We will switch back to Nextcloud as the main service and use OnlyOffice only as document server. 

Thanks for you support!
